// <auto-generated />
using System;
using DBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241122140456_MoreSeeds")]
    partial class MoreSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBase.Models.Customer", b =>
                {
                    b.Property<Guid>("ID_Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID_Customer");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID_Customer = new Guid("9968614d-c178-4d2d-948f-00d3372b7557"),
                            Address = "123 Main St, Anytown, USA",
                            Auto = 0,
                            CustomerName = "John Doe",
                            Email = "john.doe@example.com",
                            Phone = "111-222-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("3b3ef280-6b8a-40e0-b0f4-6f0242a28e56"),
                            Address = "456 Elm St, Othertown, USA",
                            Auto = 0,
                            CustomerName = "Jane Smith",
                            Email = "jane.smith@example.com",
                            Phone = "444-555-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("91527ea6-09c5-4459-9084-444843fd99f3"),
                            Address = "789 Pine St, Sometown, USA",
                            Auto = 0,
                            CustomerName = "Alice Johnson",
                            Email = "alice.johnson@example.com",
                            Phone = "222-333-4444"
                        },
                        new
                        {
                            ID_Customer = new Guid("db64165e-c9c5-4902-95d4-2bdfae7e6a9e"),
                            Address = "321 Oak St, Anothertown, USA",
                            Auto = 0,
                            CustomerName = "Bob Brown",
                            Email = "bob.brown@example.com",
                            Phone = "555-666-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("7fe5c280-66aa-441f-9d60-8c63a9c38889"),
                            Address = "135 Maple St, Newtown, USA",
                            Auto = 0,
                            CustomerName = "Charlie Davis",
                            Email = "charlie.davis@example.com",
                            Phone = "888-999-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("55fafe62-99d7-4f37-9978-be4d1ed93056"),
                            Address = "246 Cedar St, Oldtown, USA",
                            Auto = 0,
                            CustomerName = "Diana Prince",
                            Email = "diana.prince@example.com",
                            Phone = "777-888-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("7f76aca1-32ea-4c94-b039-fd4e1af0cfcc"),
                            Address = "357 Birch St, Yourtown, USA",
                            Auto = 0,
                            CustomerName = "Ethan Hunt",
                            Email = "ethan.hunt@example.com",
                            Phone = "333-444-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("c73a201d-d6fa-4647-a899-66a212ebec48"),
                            Address = "468 Spruce St, Hometown, USA",
                            Auto = 0,
                            CustomerName = "Fiona Green",
                            Email = "fiona.green@example.com",
                            Phone = "666-777-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("ce280b61-edc2-4b48-ad0d-c4aece68967e"),
                            Address = "579 Fir St, Thistown, USA",
                            Auto = 0,
                            CustomerName = "George White",
                            Email = "george.white@example.com",
                            Phone = "999-000-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("c3279e8a-949a-41ba-80b7-915d431edcb6"),
                            Address = "680 Willow St, Thatown, USA",
                            Auto = 0,
                            CustomerName = "Hannah Blue",
                            Email = "hannah.blue@example.com",
                            Phone = "222-111-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("70b4da1e-7b0c-4fa9-81bb-212f2784d32c"),
                            Address = "791 Ash St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Ian Gray",
                            Email = "ian.gray@example.com",
                            Phone = "444-222-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("78be7ef6-b1bd-4983-a74d-e8d6df827c95"),
                            Address = "802 Cherry St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Julia Red",
                            Email = "julia.red@example.com",
                            Phone = "555-333-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("c44cdd70-aab1-4609-bf89-d3adb04f04e5"),
                            Address = "913 Peach St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Kevin Black",
                            Email = "kevin.black@example.com",
                            Phone = "666-444-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("77fa4da5-d422-4df1-9ba2-9fad50a15522"),
                            Address = "024 Plum St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Laura Pink",
                            Email = "laura.pink@example.com",
                            Phone = "777-555-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("e40966e7-be50-4271-9ca7-bc0c462fd562"),
                            Address = "135 Lemon St, Oldcity, USA",
                            Auto = 0,
                            CustomerName = "Mike Yellow",
                            Email = "mike.yellow@example.com",
                            Phone = "888-666-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("7df36448-61d5-4691-b5df-7d85497b5c2b"),
                            Address = "246 Lime St, Yourcity, USA",
                            Auto = 0,
                            CustomerName = "Nina Cyan",
                            Email = "nina.cyan@example.com",
                            Phone = "999-777-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("4fe91387-85a8-49b8-b1d3-658d202ce9b0"),
                            Address = "357 Grape St, Thatcity, USA",
                            Auto = 0,
                            CustomerName = "Oscar Magenta",
                            Email = "oscar.magenta@example.com",
                            Phone = "000-888-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("1bff5891-57fa-428f-99e2-3536d3510c76"),
                            Address = "468 Berry St, Thiscity, USA",
                            Auto = 0,
                            CustomerName = "Paula Teal",
                            Email = "paula.teal@example.com",
                            Phone = "111-999-2222"
                        },
                        new
                        {
                            ID_Customer = new Guid("a4be202c-5dcf-47a3-9b10-a01a17895efc"),
                            Address = "579 Fig St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Quinn Brown",
                            Email = "quinn.brown@example.com",
                            Phone = "222-000-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("c59ae328-7ab8-4eaf-9093-be0581921dff"),
                            Address = "680 Date St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Rachel Silver",
                            Email = "rachel.silver@example.com",
                            Phone = "333-111-4444"
                        },
                        new
                        {
                            ID_Customer = new Guid("a22af5cd-77d4-4e16-8c69-25109af63219"),
                            Address = "791 Olive St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Steve Gold",
                            Email = "steve.gold@example.com",
                            Phone = "444-222-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("ce0d2f02-0212-4938-853e-af303be593da"),
                            Address = "802 Walnut St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Tina Copper",
                            Email = "tina.copper@example.com",
                            Phone = "555-333-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("a67b611d-5283-457b-862b-a1c202e07885"),
                            Address = "913 Chestnut St, Oldcity, USA",
                            Auto = 0,
                            CustomerName = "Ursula Bronze",
                            Email = "ursula.bronze@example.com",
                            Phone = "666-444-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("f7c19f58-f85a-4d26-9433-bf1d720e00b7"),
                            Address = "024 Maple St, Yourcity, USA",
                            Auto = 0,
                            CustomerName = "Victor Steel",
                            Email = "victor.steel@example.com",
                            Phone = "777-555-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("92d95be7-a2c2-4bd5-aca5-6f1cc13d2829"),
                            Address = "135 Pineapple St, Thatcity, USA",
                            Auto = 0,
                            CustomerName = "Wendy Iron",
                            Email = "wendy.iron@example.com",
                            Phone = "888-666-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("ca6fbe44-afce-43ee-8fdf-a0e873fd6e75"),
                            Address = "246 Coconut St, Thiscity, USA",
                            Auto = 0,
                            CustomerName = "Xander Zinc",
                            Email = "xander.zinc@example.com",
                            Phone = "999-777-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("9088e531-a9e2-4d12-885e-1fab1a3ef4a9"),
                            Address = "357 Papaya St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Yvonne Nickel",
                            Email = "yvonne.nickel@example.com",
                            Phone = "000-888-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("d6111caa-3080-40aa-a929-59f4543a2c6c"),
                            Address = "680 Kiwi St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Zachary Lead",
                            Email = "zachary.lead@example.com",
                            Phone = "111-999-2222"
                        },
                        new
                        {
                            ID_Customer = new Guid("e49fb541-fcb1-4efc-a1eb-bd4781340fcf"),
                            Address = "791 Mango St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Alice Cooper",
                            Email = "alice.cooper@example.com",
                            Phone = "222-000-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("000560d5-8ca4-4139-bd4f-332113b252ea"),
                            Address = "802 Banana St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Bob Marley",
                            Email = "bob.marley@example.com",
                            Phone = "333-111-4444"
                        });
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.Property<Guid>("ID_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Order");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID_Order = new Guid("b24b920d-d5a7-4775-b27d-3df293c626d3"),
                            Auto = 0,
                            CustomerID = new Guid("9968614d-c178-4d2d-948f-00d3372b7557"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(196),
                            Status = "Completed",
                            TotalAmount = 35.00m
                        },
                        new
                        {
                            ID_Order = new Guid("97ec1e5f-8749-4222-9ea5-32b6149417b0"),
                            Auto = 0,
                            CustomerID = new Guid("3b3ef280-6b8a-40e0-b0f4-6f0242a28e56"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(203),
                            Status = "Pending",
                            TotalAmount = 20.00m
                        },
                        new
                        {
                            ID_Order = new Guid("0fe8b904-2a93-4382-8586-cf0b6f889cfd"),
                            Auto = 0,
                            CustomerID = new Guid("91527ea6-09c5-4459-9084-444843fd99f3"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(209),
                            Status = "Completed",
                            TotalAmount = 80.00m
                        },
                        new
                        {
                            ID_Order = new Guid("ad90ee49-6232-4d23-893a-c7156a77cf5d"),
                            Auto = 0,
                            CustomerID = new Guid("db64165e-c9c5-4902-95d4-2bdfae7e6a9e"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(215),
                            Status = "Shipped",
                            TotalAmount = 70.00m
                        },
                        new
                        {
                            ID_Order = new Guid("c6e7ec3b-46ad-405e-a991-a02ca6a8e4ba"),
                            Auto = 0,
                            CustomerID = new Guid("7fe5c280-66aa-441f-9d60-8c63a9c38889"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(222),
                            Status = "Completed",
                            TotalAmount = 300.50m
                        },
                        new
                        {
                            ID_Order = new Guid("86de8a5e-5aac-4055-87d0-c987a492b78d"),
                            Auto = 0,
                            CustomerID = new Guid("55fafe62-99d7-4f37-9978-be4d1ed93056"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(227),
                            Status = "Pending",
                            TotalAmount = 300.50m
                        },
                        new
                        {
                            ID_Order = new Guid("4247b966-c5e1-437d-9ca8-de358f8214b0"),
                            Auto = 0,
                            CustomerID = new Guid("7f76aca1-32ea-4c94-b039-fd4e1af0cfcc"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(233),
                            Status = "Shipped",
                            TotalAmount = 6000.50m
                        },
                        new
                        {
                            ID_Order = new Guid("6a4616a6-6776-4633-b811-26fc5372b568"),
                            Auto = 0,
                            CustomerID = new Guid("c73a201d-d6fa-4647-a899-66a212ebec48"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(239),
                            Status = "Completed",
                            TotalAmount = 5001.30m
                        },
                        new
                        {
                            ID_Order = new Guid("5395a48c-db13-45eb-996f-081a02914be8"),
                            Auto = 0,
                            CustomerID = new Guid("ce280b61-edc2-4b48-ad0d-c4aece68967e"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(245),
                            Status = "Pending",
                            TotalAmount = 1100.20m
                        },
                        new
                        {
                            ID_Order = new Guid("d32a5232-c659-486c-bd9a-9284a768c923"),
                            Auto = 0,
                            CustomerID = new Guid("c3279e8a-949a-41ba-80b7-915d431edcb6"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(250),
                            Status = "Completed",
                            TotalAmount = 3500.00m
                        },
                        new
                        {
                            ID_Order = new Guid("1bf16c75-1a5d-4c23-a0df-87e723493599"),
                            Auto = 0,
                            CustomerID = new Guid("70b4da1e-7b0c-4fa9-81bb-212f2784d32c"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(255),
                            Status = "Pending",
                            TotalAmount = 800.00m
                        },
                        new
                        {
                            ID_Order = new Guid("d1e44f99-3d8e-4e38-b2b0-be5e71151431"),
                            Auto = 0,
                            CustomerID = new Guid("78be7ef6-b1bd-4983-a74d-e8d6df827c95"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(261),
                            Status = "Shipped",
                            TotalAmount = 1400.20m
                        },
                        new
                        {
                            ID_Order = new Guid("7fabd021-404b-458a-9e50-aa8e3add31f6"),
                            Auto = 0,
                            CustomerID = new Guid("c44cdd70-aab1-4609-bf89-d3adb04f04e5"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(266),
                            Status = "Completed",
                            TotalAmount = 3201.00m
                        },
                        new
                        {
                            ID_Order = new Guid("78ab56cb-4c81-4cd8-9418-8a53e5219cfc"),
                            Auto = 0,
                            CustomerID = new Guid("77fa4da5-d422-4df1-9ba2-9fad50a15522"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 4, 55, 699, DateTimeKind.Utc).AddTicks(272),
                            Status = "Pending",
                            TotalAmount = 6300.80m
                        });
                });

            modelBuilder.Entity("DBase.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("ID_OrderDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ID_OrderDetails");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            ID_OrderDetails = new Guid("1b272d79-4c1e-4bce-ada6-5594ddb1c112"),
                            Auto = 0,
                            OrderId = new Guid("b24b920d-d5a7-4775-b27d-3df293c626d3"),
                            ProductId = new Guid("5b433591-26b1-4ae9-8922-118a1156a635"),
                            Quantity = 2,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("1737176d-fe85-4074-b5ef-fbe64fedf6e8"),
                            Auto = 0,
                            OrderId = new Guid("b24b920d-d5a7-4775-b27d-3df293c626d3"),
                            ProductId = new Guid("28367500-eb25-4f02-882f-c90c64af5ec6"),
                            Quantity = 1,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("200c167d-d9a6-40eb-b820-8509d65161d8"),
                            Auto = 0,
                            OrderId = new Guid("97ec1e5f-8749-4222-9ea5-32b6149417b0"),
                            ProductId = new Guid("a6794630-264d-4da1-a35d-651c4ee0f00d"),
                            Quantity = 1,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("f54dfe74-bad7-4151-9e2d-b329811dfed8"),
                            Auto = 0,
                            OrderId = new Guid("0fe8b904-2a93-4382-8586-cf0b6f889cfd"),
                            ProductId = new Guid("88ef40aa-9911-4916-9130-1c9f07175c9a"),
                            Quantity = 2,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("9192827e-ac17-4779-91a6-3d5241c2ef1f"),
                            Auto = 0,
                            OrderId = new Guid("0fe8b904-2a93-4382-8586-cf0b6f889cfd"),
                            ProductId = new Guid("3d463c1e-f535-417d-b478-a720d306ed01"),
                            Quantity = 1,
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("97be6a03-5f45-4bb0-8940-fafbd7150263"),
                            Auto = 0,
                            OrderId = new Guid("ad90ee49-6232-4d23-893a-c7156a77cf5d"),
                            ProductId = new Guid("11f2b8bb-f6ec-4a61-a1f5-ad0c7eb9ce85"),
                            Quantity = 2,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("6609766b-0f15-4a38-889e-1ba03f405a11"),
                            Auto = 0,
                            OrderId = new Guid("c6e7ec3b-46ad-405e-a991-a02ca6a8e4ba"),
                            ProductId = new Guid("d9a5f831-e4fe-42c6-bbfa-d21fca5741dd"),
                            Quantity = 1,
                            UnitPrice = 100.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("c42ae8f3-f999-46e6-803a-10b5ffdc5636"),
                            Auto = 0,
                            OrderId = new Guid("c6e7ec3b-46ad-405e-a991-a02ca6a8e4ba"),
                            ProductId = new Guid("c5d44187-c0f1-414e-95d1-a0d4ef427dcc"),
                            Quantity = 1,
                            UnitPrice = 200.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("e3e3ad0e-d043-4601-8d48-ef4196951a8b"),
                            Auto = 0,
                            OrderId = new Guid("86de8a5e-5aac-4055-87d0-c987a492b78d"),
                            ProductId = new Guid("0e1efc12-6035-4d18-8ead-a1b9203dd841"),
                            Quantity = 1,
                            UnitPrice = 300.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("022ce0ca-e5c1-4234-847d-c8a39e2c93d1"),
                            Auto = 0,
                            OrderId = new Guid("4247b966-c5e1-437d-9ca8-de358f8214b0"),
                            ProductId = new Guid("aaaac5d2-8576-48e9-b348-2aedca1650f5"),
                            Quantity = 1,
                            UnitPrice = 4000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("2b74da7a-beff-4542-9c80-2cc5d5993b53"),
                            Auto = 0,
                            OrderId = new Guid("4247b966-c5e1-437d-9ca8-de358f8214b0"),
                            ProductId = new Guid("01e9c78b-d3ca-4133-a72c-55ba67085521"),
                            Quantity = 1,
                            UnitPrice = 2000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("1d1b9000-70a6-49fe-b8ad-91a0086bdd47"),
                            Auto = 0,
                            OrderId = new Guid("6a4616a6-6776-4633-b811-26fc5372b568"),
                            ProductId = new Guid("729ec85d-fa0d-477b-8005-8899c4599a41"),
                            Quantity = 1,
                            UnitPrice = 1000.80m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("1776dc33-5602-4ce2-ba94-e9cb5de5e9d5"),
                            Auto = 0,
                            OrderId = new Guid("6a4616a6-6776-4633-b811-26fc5372b568"),
                            ProductId = new Guid("446eb2d5-9ab6-401a-bb5a-380465afca6d"),
                            Quantity = 1,
                            UnitPrice = 4000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("a5e49eec-e167-4347-bbd5-ec6db894fd3d"),
                            Auto = 0,
                            OrderId = new Guid("5395a48c-db13-45eb-996f-081a02914be8"),
                            ProductId = new Guid("3f4810d0-2338-460d-9f80-f3c39699af53"),
                            Quantity = 1,
                            UnitPrice = 6000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("666ed0c4-651f-4b19-a04a-75b2da4416ac"),
                            Auto = 0,
                            OrderId = new Guid("5395a48c-db13-45eb-996f-081a02914be8"),
                            ProductId = new Guid("9f1c1f9b-87f2-4f6e-a0af-b3228c7c4d15"),
                            Quantity = 1,
                            UnitPrice = 3000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("6848c3bd-21ca-4be2-8d7c-2890399b127c"),
                            Auto = 0,
                            OrderId = new Guid("5395a48c-db13-45eb-996f-081a02914be8"),
                            ProductId = new Guid("f924bda0-f643-4b8f-88e8-5272e4f044de"),
                            Quantity = 1,
                            UnitPrice = 2000.20m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("837877f6-9d48-41c4-a35d-5d62faebe422"),
                            Auto = 0,
                            OrderId = new Guid("d32a5232-c659-486c-bd9a-9284a768c923"),
                            ProductId = new Guid("189d7451-0786-461c-8fba-7705e8e33ac6"),
                            Quantity = 1,
                            UnitPrice = 3000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("fd205d81-28ab-4ffc-a607-b5960164c926"),
                            Auto = 0,
                            OrderId = new Guid("d32a5232-c659-486c-bd9a-9284a768c923"),
                            ProductId = new Guid("5aad2270-ff2f-43e3-b655-2b819d1b3471"),
                            Quantity = 1,
                            UnitPrice = 500.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("a7e65e60-2fd2-4a81-8760-0a1362f007c8"),
                            Auto = 0,
                            OrderId = new Guid("1bf16c75-1a5d-4c23-a0df-87e723493599"),
                            ProductId = new Guid("83572000-5201-4653-bc78-7a4b483a50f4"),
                            Quantity = 1,
                            UnitPrice = 800.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("33be799f-5c9b-4ea3-93a3-35fb52fdfbc9"),
                            Auto = 0,
                            OrderId = new Guid("d1e44f99-3d8e-4e38-b2b0-be5e71151431"),
                            ProductId = new Guid("12383e39-59ec-4c76-b5df-d74e455b379a"),
                            Quantity = 1,
                            UnitPrice = 1000.20m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("65676a57-4edb-4e5f-9290-12599dfd62fa"),
                            Auto = 0,
                            OrderId = new Guid("d1e44f99-3d8e-4e38-b2b0-be5e71151431"),
                            ProductId = new Guid("bbf39327-3ebe-4ca3-9789-d334c45c4654"),
                            Quantity = 1,
                            UnitPrice = 400.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("d027667a-dd9b-46e1-af4a-d7e18afc143e"),
                            Auto = 0,
                            OrderId = new Guid("7fabd021-404b-458a-9e50-aa8e3add31f6"),
                            ProductId = new Guid("8b300791-586f-4061-bef6-6d6b88e12240"),
                            Quantity = 1,
                            UnitPrice = 3000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("89b02f07-0cc4-4db8-b7eb-fc43e7b6d15d"),
                            Auto = 0,
                            OrderId = new Guid("7fabd021-404b-458a-9e50-aa8e3add31f6"),
                            ProductId = new Guid("4485e0fa-8f90-4348-8676-2769eb6ba5e8"),
                            Quantity = 1,
                            UnitPrice = 200.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("e997f342-5d97-4526-b232-d8d26bc8c4f7"),
                            Auto = 0,
                            OrderId = new Guid("78ab56cb-4c81-4cd8-9418-8a53e5219cfc"),
                            ProductId = new Guid("d2b8687a-070a-4817-96e3-365bebb693c4"),
                            Quantity = 1,
                            UnitPrice = 100.80m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("bd5212d7-f0f6-4d94-8d65-a1c76beb0407"),
                            Auto = 0,
                            OrderId = new Guid("78ab56cb-4c81-4cd8-9418-8a53e5219cfc"),
                            ProductId = new Guid("c2685135-2196-483b-b6f9-c397b56b4870"),
                            Quantity = 1,
                            UnitPrice = 200.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("51444ade-1717-4f68-8e1b-5a227f01de7a"),
                            Auto = 0,
                            OrderId = new Guid("78ab56cb-4c81-4cd8-9418-8a53e5219cfc"),
                            ProductId = new Guid("cd435b50-146c-4b35-8aaa-df60255589b8"),
                            Quantity = 1,
                            UnitPrice = 6000.00m
                        });
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.Property<Guid>("ID_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("Cell")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Producer")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WarehouseID")
                        .HasColumnType("uuid");

                    b.HasKey("ID_Product");

                    b.HasIndex("SupplierID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID_Product = new Guid("5b433591-26b1-4ae9-8922-118a1156a635"),
                            Auto = 0,
                            Cell = "a100",
                            Producer = "Producer 1",
                            ProductName = "Product 1",
                            QuantityInStock = 100,
                            SupplierID = new Guid("9c6a8113-ba44-4b94-bebf-31aacb96a183"),
                            UnitPrice = 10.00m,
                            WarehouseID = new Guid("e4a36000-c5c6-4836-999b-57b3a5f5ce6c")
                        },
                        new
                        {
                            ID_Product = new Guid("28367500-eb25-4f02-882f-c90c64af5ec6"),
                            Auto = 0,
                            Cell = "a101",
                            Producer = "Producer 2",
                            ProductName = "Product 2",
                            QuantityInStock = 200,
                            SupplierID = new Guid("9c6a8113-ba44-4b94-bebf-31aacb96a183"),
                            UnitPrice = 15.00m,
                            WarehouseID = new Guid("e4a36000-c5c6-4836-999b-57b3a5f5ce6c")
                        },
                        new
                        {
                            ID_Product = new Guid("a6794630-264d-4da1-a35d-651c4ee0f00d"),
                            Auto = 0,
                            Cell = "a102",
                            Producer = "Producer 2",
                            ProductName = "Product 3",
                            QuantityInStock = 150,
                            SupplierID = new Guid("13af075e-a923-42fc-a866-6b0cfe6b79d6"),
                            UnitPrice = 20.00m,
                            WarehouseID = new Guid("ac73118a-f69f-423a-aa64-f4b01dfdcafc")
                        },
                        new
                        {
                            ID_Product = new Guid("88ef40aa-9911-4916-9130-1c9f07175c9a"),
                            Auto = 0,
                            Cell = "a103",
                            Producer = "Producer 2",
                            ProductName = "Product 4",
                            QuantityInStock = 80,
                            SupplierID = new Guid("eb180958-e017-4e60-8e78-df8f361c9bf6"),
                            UnitPrice = 25.00m,
                            WarehouseID = new Guid("c447c363-4528-437c-ae09-41d9304e6594")
                        },
                        new
                        {
                            ID_Product = new Guid("3d463c1e-f535-417d-b478-a720d306ed01"),
                            Auto = 0,
                            Cell = "a104",
                            Producer = "Producer 3",
                            ProductName = "Product 5",
                            QuantityInStock = 60,
                            SupplierID = new Guid("eb180958-e017-4e60-8e78-df8f361c9bf6"),
                            UnitPrice = 30.00m,
                            WarehouseID = new Guid("c447c363-4528-437c-ae09-41d9304e6594")
                        },
                        new
                        {
                            ID_Product = new Guid("11f2b8bb-f6ec-4a61-a1f5-ad0c7eb9ce85"),
                            Auto = 0,
                            Cell = "a105",
                            Producer = "Producer 3",
                            ProductName = "Product 6",
                            QuantityInStock = 40,
                            SupplierID = new Guid("9ecd1896-b951-40f8-b13d-91a4b1bf09f3"),
                            UnitPrice = 35.00m,
                            WarehouseID = new Guid("25f075a3-d55d-4a93-ad67-1ec095dc4597")
                        },
                        new
                        {
                            ID_Product = new Guid("d9a5f831-e4fe-42c6-bbfa-d21fca5741dd"),
                            Auto = 0,
                            Cell = "a10",
                            Producer = "Fresh Farms",
                            ProductName = "Organic Apples",
                            QuantityInStock = 150,
                            SupplierID = new Guid("88cfa22b-02fa-468f-9aeb-7fa8f81e01dc"),
                            UnitPrice = 100.50m,
                            WarehouseID = new Guid("c774729c-690c-4c53-8468-3c73e8ffb632")
                        },
                        new
                        {
                            ID_Product = new Guid("c5d44187-c0f1-414e-95d1-a0d4ef427dcc"),
                            Auto = 0,
                            Cell = "a11",
                            Producer = "Bakery Co.",
                            ProductName = "Whole Wheat Bread",
                            QuantityInStock = 200,
                            SupplierID = new Guid("88cfa22b-02fa-468f-9aeb-7fa8f81e01dc"),
                            UnitPrice = 200.00m,
                            WarehouseID = new Guid("c774729c-690c-4c53-8468-3c73e8ffb632")
                        },
                        new
                        {
                            ID_Product = new Guid("0e1efc12-6035-4d18-8ead-a1b9203dd841"),
                            Auto = 0,
                            Cell = "a12",
                            Producer = "Nutty Delights",
                            ProductName = "Almond Milk",
                            QuantityInStock = 100,
                            SupplierID = new Guid("939a8fb8-8dba-4a34-abea-2a9b85aa1655"),
                            UnitPrice = 300.50m,
                            WarehouseID = new Guid("f8f8d9e9-90e4-49ad-9336-2b2dc0fc35e3")
                        },
                        new
                        {
                            ID_Product = new Guid("aaaac5d2-8576-48e9-b348-2aedca1650f5"),
                            Auto = 0,
                            Cell = "a13",
                            Producer = "Dairy Best",
                            ProductName = "Greek Yogurt",
                            QuantityInStock = 80,
                            SupplierID = new Guid("939a8fb8-8dba-4a34-abea-2a9b85aa1655"),
                            UnitPrice = 4000.00m,
                            WarehouseID = new Guid("b0537ac5-d718-4d97-9638-d43f7d203885")
                        },
                        new
                        {
                            ID_Product = new Guid("01e9c78b-d3ca-4133-a72c-55ba67085521"),
                            Auto = 0,
                            Cell = "a14",
                            Producer = "Farm Fresh",
                            ProductName = "Free-Range Eggs",
                            QuantityInStock = 60,
                            SupplierID = new Guid("939a8fb8-8dba-4a34-abea-2a9b85aa1655"),
                            UnitPrice = 2000.50m,
                            WarehouseID = new Guid("b0537ac5-d718-4d97-9638-d43f7d203885")
                        },
                        new
                        {
                            ID_Product = new Guid("729ec85d-fa0d-477b-8005-8899c4599a41"),
                            Auto = 0,
                            Cell = "a15",
                            Producer = "Grain Masters",
                            ProductName = "Brown Rice",
                            QuantityInStock = 120,
                            SupplierID = new Guid("376d4527-7957-45c3-bc0e-fe2b2c11205a"),
                            UnitPrice = 1000.80m,
                            WarehouseID = new Guid("3232ab97-72d0-4a78-9ba9-b9a69b1d7cde")
                        },
                        new
                        {
                            ID_Product = new Guid("446eb2d5-9ab6-401a-bb5a-380465afca6d"),
                            Auto = 0,
                            Cell = "a106",
                            Producer = "Healthy Grains",
                            ProductName = "Quinoa",
                            QuantityInStock = 90,
                            SupplierID = new Guid("376d4527-7957-45c3-bc0e-fe2b2c11205a"),
                            UnitPrice = 4000.50m,
                            WarehouseID = new Guid("3232ab97-72d0-4a78-9ba9-b9a69b1d7cde")
                        },
                        new
                        {
                            ID_Product = new Guid("3f4810d0-2338-460d-9f80-f3c39699af53"),
                            Auto = 0,
                            Cell = "a107",
                            Producer = "Tropical Goods",
                            ProductName = "Coconut Oil",
                            QuantityInStock = 70,
                            SupplierID = new Guid("376d4527-7957-45c3-bc0e-fe2b2c11205a"),
                            UnitPrice = 6000.00m,
                            WarehouseID = new Guid("f8f8d9e9-90e4-49ad-9336-2b2dc0fc35e3")
                        },
                        new
                        {
                            ID_Product = new Guid("9f1c1f9b-87f2-4f6e-a0af-b3228c7c4d15"),
                            Auto = 0,
                            Cell = "a108",
                            Producer = "Choco Bliss",
                            ProductName = "Dark Chocolate",
                            QuantityInStock = 50,
                            SupplierID = new Guid("85e16251-16ae-411a-9314-2f917a2b65e2"),
                            UnitPrice = 3000.00m,
                            WarehouseID = new Guid("d014bdd3-018a-4b71-a1c1-7fb2594643de")
                        },
                        new
                        {
                            ID_Product = new Guid("f924bda0-f643-4b8f-88e8-5272e4f044de"),
                            Auto = 0,
                            Cell = "a109",
                            Producer = "Green Leaf",
                            ProductName = "Spinach",
                            QuantityInStock = 110,
                            SupplierID = new Guid("124127e1-9781-4556-8e33-3283fc113f91"),
                            UnitPrice = 2000.20m,
                            WarehouseID = new Guid("cc50f20e-acbd-4667-bac5-71da8e43938e")
                        },
                        new
                        {
                            ID_Product = new Guid("189d7451-0786-461c-8fba-7705e8e33ac6"),
                            Auto = 0,
                            Cell = "a110",
                            Producer = "Healthy Mornings",
                            ProductName = "Oatmeal",
                            QuantityInStock = 200,
                            SupplierID = new Guid("7c0c3b60-8a06-4572-8b1a-ae5efb34f507"),
                            UnitPrice = 3000.00m,
                            WarehouseID = new Guid("c447c363-4528-437c-ae09-41d9304e6594")
                        },
                        new
                        {
                            ID_Product = new Guid("5aad2270-ff2f-43e3-b655-2b819d1b3471"),
                            Auto = 0,
                            Cell = "a111",
                            Producer = "Superfoods Co.",
                            ProductName = "Chia Seeds",
                            QuantityInStock = 150,
                            SupplierID = new Guid("d8920fb8-b027-46e1-be6d-66e3808c8f9b"),
                            UnitPrice = 500.00m,
                            WarehouseID = new Guid("9109fa2b-a485-4f3c-b657-5271a8bea7de")
                        },
                        new
                        {
                            ID_Product = new Guid("83572000-5201-4653-bc78-7a4b483a50f4"),
                            Auto = 0,
                            Cell = "a112",
                            Producer = "Nature's Best",
                            ProductName = "Avocado Oil",
                            QuantityInStock = 80,
                            SupplierID = new Guid("1cdbe5db-4292-4fb5-9601-1773ac101eea"),
                            UnitPrice = 800.00m,
                            WarehouseID = new Guid("b0537ac5-d718-4d97-9638-d43f7d203885")
                        },
                        new
                        {
                            ID_Product = new Guid("12383e39-59ec-4c76-b5df-d74e455b379a"),
                            Auto = 0,
                            Cell = "a113",
                            Producer = "Legume Lovers",
                            ProductName = "Canned Chickpeas",
                            QuantityInStock = 300,
                            SupplierID = new Guid("a0506634-cc3e-414e-860c-f9ae15d1daf8"),
                            UnitPrice = 1000.20m,
                            WarehouseID = new Guid("3232ab97-72d0-4a78-9ba9-b9a69b1d7cde")
                        },
                        new
                        {
                            ID_Product = new Guid("bbf39327-3ebe-4ca3-9789-d334c45c4654"),
                            Auto = 0,
                            Cell = "a114",
                            Producer = "Berry Good",
                            ProductName = "Frozen Berries",
                            QuantityInStock = 120,
                            SupplierID = new Guid("22c39cb1-24bb-43c2-b60e-aa655031e4f6"),
                            UnitPrice = 400.00m,
                            WarehouseID = new Guid("f8f8d9e9-90e4-49ad-9336-2b2dc0fc35e3")
                        },
                        new
                        {
                            ID_Product = new Guid("8b300791-586f-4061-bef6-6d6b88e12240"),
                            Auto = 0,
                            Cell = "a115",
                            Producer = "Nutty Spread",
                            ProductName = "Peanut Butter",
                            QuantityInStock = 90,
                            SupplierID = new Guid("f1404bea-0c13-4c3c-8608-72a4cf1142ea"),
                            UnitPrice = 3000.50m,
                            WarehouseID = new Guid("3312aa85-d4a2-46d0-b8fc-3a504a2108e4")
                        },
                        new
                        {
                            ID_Product = new Guid("4485e0fa-8f90-4348-8676-2769eb6ba5e8"),
                            Auto = 0,
                            Cell = "a116",
                            Producer = "Tropical Refreshments",
                            ProductName = "Coconut Water",
                            QuantityInStock = 200,
                            SupplierID = new Guid("6c074e28-87e7-4ad2-8562-8c4b3d4862c2"),
                            UnitPrice = 200.50m,
                            WarehouseID = new Guid("f0d04b50-203a-436f-abb2-0225b006ad16")
                        },
                        new
                        {
                            ID_Product = new Guid("d2b8687a-070a-4817-96e3-365bebb693c4"),
                            Auto = 0,
                            Cell = "a117",
                            Producer = "Snack Time",
                            ProductName = "Granola Bars",
                            QuantityInStock = 150,
                            SupplierID = new Guid("f5240207-4281-4dbf-8d12-ce189e3fe3e6"),
                            UnitPrice = 100.80m,
                            WarehouseID = new Guid("d014bdd3-018a-4b71-a1c1-7fb2594643de")
                        },
                        new
                        {
                            ID_Product = new Guid("c2685135-2196-483b-b6f9-c397b56b4870"),
                            Auto = 0,
                            Cell = "a118",
                            Producer = "Dips & Spreads",
                            ProductName = "Hummus",
                            QuantityInStock = 100,
                            SupplierID = new Guid("04d1efb8-0849-4f39-9d22-c618d529756c"),
                            UnitPrice = 200.00m,
                            WarehouseID = new Guid("cc50f20e-acbd-4667-bac5-71da8e43938e")
                        },
                        new
                        {
                            ID_Product = new Guid("cd435b50-146c-4b35-8aaa-df60255589b8"),
                            Auto = 0,
                            Cell = "a119",
                            Producer = "Sweet Harvest",
                            ProductName = "Maple Syrup",
                            QuantityInStock = 70,
                            SupplierID = new Guid("ef76beb7-0876-49ef-9dd1-eb309bd07269"),
                            UnitPrice = 6000.00m,
                            WarehouseID = new Guid("12158fdf-5485-4df7-9842-3b49d240bdec")
                        },
                        new
                        {
                            ID_Product = new Guid("cb3845d9-64d2-4c9e-afc6-4a0aac33fdbd"),
                            Auto = 0,
                            Cell = "a126",
                            Producer = "Root Veggies",
                            ProductName = "Sweet Potatoes",
                            QuantityInStock = 120,
                            SupplierID = new Guid("eb180958-e017-4e60-8e78-df8f361c9bf6"),
                            UnitPrice = 100.80m,
                            WarehouseID = new Guid("c447c363-4528-437c-ae09-41d9304e6594")
                        },
                        new
                        {
                            ID_Product = new Guid("a980e830-1ec8-4cb3-b07d-fce0badc7cbf"),
                            Auto = 0,
                            Cell = "a127",
                            Producer = "Garden Fresh",
                            ProductName = "Canned Tomatoes",
                            QuantityInStock = 300,
                            SupplierID = new Guid("9ecd1896-b951-40f8-b13d-91a4b1bf09f3"),
                            UnitPrice = 1000.00m,
                            WarehouseID = new Guid("25f075a3-d55d-4a93-ad67-1ec095dc4597")
                        },
                        new
                        {
                            ID_Product = new Guid("015cd4a6-7581-40ff-9d9f-bf2abe283b02"),
                            Auto = 0,
                            Cell = "a128",
                            Producer = "Healthy Snacks",
                            ProductName = "Nut Mix",
                            QuantityInStock = 90,
                            SupplierID = new Guid("13af075e-a923-42fc-a866-6b0cfe6b79d6"),
                            UnitPrice = 600.00m,
                            WarehouseID = new Guid("ac73118a-f69f-423a-aa64-f4b01dfdcafc")
                        },
                        new
                        {
                            ID_Product = new Guid("ac9e84c9-b819-4a75-a0f0-978874753705"),
                            Auto = 0,
                            Cell = "a129",
                            Producer = "Gourmet Essentials",
                            ProductName = "Balsamic Vinegar",
                            QuantityInStock = 70,
                            SupplierID = new Guid("9c6a8113-ba44-4b94-bebf-31aacb96a183"),
                            UnitPrice = 4000.50m,
                            WarehouseID = new Guid("e4a36000-c5c6-4836-999b-57b3a5f5ce6c")
                        },
                        new
                        {
                            ID_Product = new Guid("f5f33578-1f17-48ee-b04a-3d2e3b74edeb"),
                            Auto = 0,
                            Cell = "a130",
                            Producer = "Plant Protein Co.",
                            ProductName = "Tofu",
                            QuantityInStock = 100,
                            SupplierID = new Guid("ef76beb7-0876-49ef-9dd1-eb309bd07269"),
                            UnitPrice = 200.50m,
                            WarehouseID = new Guid("c447c363-4528-437c-ae09-41d9304e6594")
                        },
                        new
                        {
                            ID_Product = new Guid("0f329756-e609-4306-96a9-89d9efcd7d5a"),
                            Auto = 0,
                            Cell = "a131",
                            Producer = "Nutty Delights",
                            ProductName = "Almonds",
                            QuantityInStock = 80,
                            SupplierID = new Guid("04d1efb8-0849-4f39-9d22-c618d529756c"),
                            UnitPrice = 8000.00m,
                            WarehouseID = new Guid("25f075a3-d55d-4a93-ad67-1ec095dc4597")
                        },
                        new
                        {
                            ID_Product = new Guid("a3a73285-10bc-400f-bab8-8d740c128192"),
                            Auto = 0,
                            Cell = "a132",
                            Producer = "Spice World",
                            ProductName = "Cinnamon",
                            QuantityInStock = 150,
                            SupplierID = new Guid("f5240207-4281-4dbf-8d12-ce189e3fe3e6"),
                            UnitPrice = 300.00m,
                            WarehouseID = new Guid("e4a36000-c5c6-4836-999b-57b3a5f5ce6c")
                        },
                        new
                        {
                            ID_Product = new Guid("ce30b8bc-c5f1-4431-a3eb-bcb5a22afbe3"),
                            Auto = 0,
                            Cell = "a133",
                            Producer = "Legume Lovers",
                            ProductName = "Black Beans",
                            QuantityInStock = 200,
                            SupplierID = new Guid("aae5c6fe-5eca-41d0-8984-205f938534e7"),
                            UnitPrice = 100.50m,
                            WarehouseID = new Guid("ac73118a-f69f-423a-aa64-f4b01dfdcafc")
                        },
                        new
                        {
                            ID_Product = new Guid("564ab390-fb6f-490e-9af3-4941f8907f41"),
                            Auto = 0,
                            Cell = "a134",
                            Producer = "Fresh Greens",
                            ProductName = "Cabbage",
                            QuantityInStock = 120,
                            SupplierID = new Guid("8c18cad4-c33a-4f24-8f20-e76da325fa37"),
                            UnitPrice = 166.80m,
                            WarehouseID = new Guid("c447c363-4528-437c-ae09-41d9304e6594")
                        },
                        new
                        {
                            ID_Product = new Guid("75b0e70c-1bf4-4f48-bb4c-ddc62f3a35f5"),
                            Auto = 0,
                            Cell = "a135",
                            Producer = "Healthy Harvest",
                            ProductName = "Lentils",
                            QuantityInStock = 180,
                            SupplierID = new Guid("88cfa22b-02fa-468f-9aeb-7fa8f81e01dc"),
                            UnitPrice = 177.20m,
                            WarehouseID = new Guid("25f075a3-d55d-4a93-ad67-1ec095dc4597")
                        },
                        new
                        {
                            ID_Product = new Guid("6a7dba93-3d3e-4126-88f7-843d0d8944f1"),
                            Auto = 0,
                            Cell = "a136",
                            Producer = "Snack Time",
                            ProductName = "Pumpkin Seeds",
                            QuantityInStock = 90,
                            SupplierID = new Guid("939a8fb8-8dba-4a34-abea-2a9b85aa1655"),
                            UnitPrice = 4777.00m,
                            WarehouseID = new Guid("e4a36000-c5c6-4836-999b-57b3a5f5ce6c")
                        },
                        new
                        {
                            ID_Product = new Guid("faec27f8-469a-4574-8b76-e78c1aed9da8"),
                            Auto = 0,
                            Cell = "a137",
                            Producer = "Garden Fresh",
                            ProductName = "Zucchini",
                            QuantityInStock = 150,
                            SupplierID = new Guid("13af075e-a923-42fc-a866-6b0cfe6b79d6"),
                            UnitPrice = 1777.00m,
                            WarehouseID = new Guid("ac73118a-f69f-423a-aa64-f4b01dfdcafc")
                        },
                        new
                        {
                            ID_Product = new Guid("74fe2d32-4c00-40c8-b9ce-9a7a06cd3c6e"),
                            Auto = 0,
                            Cell = "a138",
                            Producer = "Tropical Goods",
                            ProductName = "Coconut Milk",
                            QuantityInStock = 110,
                            SupplierID = new Guid("eb180958-e017-4e60-8e78-df8f361c9bf6"),
                            UnitPrice = 2777.50m,
                            WarehouseID = new Guid("c447c363-4528-437c-ae09-41d9304e6594")
                        },
                        new
                        {
                            ID_Product = new Guid("9030ecc4-5e68-4ff7-b3b6-da50bd741ea5"),
                            Auto = 0,
                            Cell = "a139",
                            Producer = "Asian Cuisine",
                            ProductName = "Rice Noodles",
                            QuantityInStock = 130,
                            SupplierID = new Guid("9ecd1896-b951-40f8-b13d-91a4b1bf09f3"),
                            UnitPrice = 3777.50m,
                            WarehouseID = new Guid("25f075a3-d55d-4a93-ad67-1ec095dc4597")
                        });
                });

            modelBuilder.Entity("DBase.Models.Supplier", b =>
                {
                    b.Property<Guid>("ID_Supplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ID_Supplier");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID_Supplier = new Guid("9c6a8113-ba44-4b94-bebf-31aacb96a183"),
                            Auto = 0,
                            ContactName = "Alice",
                            Email = "alice@supplier.com",
                            Phone = "123-456-7890",
                            SupplierName = "Supplier A"
                        },
                        new
                        {
                            ID_Supplier = new Guid("13af075e-a923-42fc-a866-6b0cfe6b79d6"),
                            Auto = 0,
                            ContactName = "Bob",
                            Email = "bob@supplier.com",
                            Phone = "098-765-4321",
                            SupplierName = "Supplier B"
                        },
                        new
                        {
                            ID_Supplier = new Guid("eb180958-e017-4e60-8e78-df8f361c9bf6"),
                            Auto = 0,
                            ContactName = "Charlie",
                            Email = "charlie@supplier.com",
                            Phone = "321-654-0987",
                            SupplierName = "Supplier C"
                        },
                        new
                        {
                            ID_Supplier = new Guid("9ecd1896-b951-40f8-b13d-91a4b1bf09f3"),
                            Auto = 0,
                            ContactName = "Diana",
                            Email = "diana@supplier.com",
                            Phone = "987-654-3210",
                            SupplierName = "Supplier D"
                        },
                        new
                        {
                            ID_Supplier = new Guid("7c0c3b60-8a06-4572-8b1a-ae5efb34f507"),
                            Auto = 0,
                            ContactName = "John Doe",
                            Email = "john.doe@acmecorp.com",
                            Phone = "555-0101",
                            SupplierName = "Acme Corp"
                        },
                        new
                        {
                            ID_Supplier = new Guid("d8920fb8-b027-46e1-be6d-66e3808c8f9b"),
                            Auto = 0,
                            ContactName = "Jane Smith",
                            Email = "jane.smith@globalsupplies.com",
                            Phone = "555-0102",
                            SupplierName = "Global Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("1cdbe5db-4292-4fb5-9601-1773ac101eea"),
                            Auto = 0,
                            ContactName = "Alice Johnson",
                            Email = "alice.johnson@techinnovations.com",
                            Phone = "555-0103",
                            SupplierName = "Tech Innovations"
                        },
                        new
                        {
                            ID_Supplier = new Guid("f1404bea-0c13-4c3c-8608-72a4cf1142ea"),
                            Auto = 0,
                            ContactName = "Bob Brown",
                            Email = "bob.brown@qualitygoods.com",
                            Phone = "555-0104",
                            SupplierName = "Quality Goods"
                        },
                        new
                        {
                            ID_Supplier = new Guid("22c39cb1-24bb-43c2-b60e-aa655031e4f6"),
                            Auto = 0,
                            ContactName = "Charlie Davis",
                            Email = "charlie.davis@fastdelivery.com",
                            Phone = "555-0105",
                            SupplierName = "Fast Delivery"
                        },
                        new
                        {
                            ID_Supplier = new Guid("a0506634-cc3e-414e-860c-f9ae15d1daf8"),
                            Auto = 0,
                            ContactName = "Diana Green",
                            Email = "diana.green@ecoproducts.com",
                            Phone = "555-0106",
                            SupplierName = "Eco Products"
                        },
                        new
                        {
                            ID_Supplier = new Guid("6c074e28-87e7-4ad2-8562-8c4b3d4862c2"),
                            Auto = 0,
                            ContactName = "Ethan White",
                            Email = "ethan.white@homeessentials.com",
                            Phone = "555-0107",
                            SupplierName = "Home Essentials"
                        },
                        new
                        {
                            ID_Supplier = new Guid("ef76beb7-0876-49ef-9dd1-eb309bd07269"),
                            Auto = 0,
                            ContactName = "Fiona Black",
                            Email = "fiona.black@officesuppliesco.com",
                            Phone = "555-0108",
                            SupplierName = "Office Supplies Co."
                        },
                        new
                        {
                            ID_Supplier = new Guid("04d1efb8-0849-4f39-9d22-c618d529756c"),
                            Auto = 0,
                            ContactName = "George Blue",
                            Email = "george.blue@gourmetfoods.com",
                            Phone = "555-0109",
                            SupplierName = "Gourmet Foods"
                        },
                        new
                        {
                            ID_Supplier = new Guid("f5240207-4281-4dbf-8d12-ce189e3fe3e6"),
                            Auto = 0,
                            ContactName = "Hannah Red",
                            Email = "hannah.red@fashionhub.com",
                            Phone = "555-0110",
                            SupplierName = "Fashion Hub"
                        },
                        new
                        {
                            ID_Supplier = new Guid("aae5c6fe-5eca-41d0-8984-205f938534e7"),
                            Auto = 0,
                            ContactName = "Ian Gray",
                            Email = "ian.gray@healthwellness.com",
                            Phone = "555-0111",
                            SupplierName = "Health & Wellness"
                        },
                        new
                        {
                            ID_Supplier = new Guid("8c18cad4-c33a-4f24-8f20-e76da325fa37"),
                            Auto = 0,
                            ContactName = "Julia Orange",
                            Email = "julia.orange@sportsgear.com",
                            Phone = "555-0112",
                            SupplierName = "Sports Gear"
                        },
                        new
                        {
                            ID_Supplier = new Guid("88cfa22b-02fa-468f-9aeb-7fa8f81e01dc"),
                            Auto = 0,
                            ContactName = "Kevin Purple",
                            Email = "kevin.purple@petsupplies.com",
                            Phone = "555-0113",
                            SupplierName = "Pet Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("939a8fb8-8dba-4a34-abea-2a9b85aa1655"),
                            Auto = 0,
                            ContactName = "Laura Pink",
                            Email = "laura.pink@automotiveparts.com",
                            Phone = "555-0114",
                            SupplierName = "Automotive Parts"
                        },
                        new
                        {
                            ID_Supplier = new Guid("376d4527-7957-45c3-bc0e-fe2b2c11205a"),
                            Auto = 0,
                            ContactName = "Mike Yellow",
                            Email = "mike.yellow@constructionmaterials.com",
                            Phone = "555-0115",
                            SupplierName = "Construction Materials"
                        },
                        new
                        {
                            ID_Supplier = new Guid("85e16251-16ae-411a-9314-2f917a2b65e2"),
                            Auto = 0,
                            ContactName = "Nina Cyan",
                            Email = "nina.cyan@beveragedistributors.com",
                            Phone = "555-0116",
                            SupplierName = "Beverage Distributors"
                        },
                        new
                        {
                            ID_Supplier = new Guid("124127e1-9781-4556-8e33-3283fc113f91"),
                            Auto = 0,
                            ContactName = "Oscar Magenta",
                            Email = "oscar.magenta@cleaningsupplies.com",
                            Phone = "555-0117",
                            SupplierName = "Cleaning Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("906e55ef-0090-41e9-a703-4d8f2509d552"),
                            Auto = 0,
                            ContactName = "Paula Teal",
                            Email = "paula.teal@furnitureworld.com",
                            Phone = "555-0118",
                            SupplierName = "Furniture World"
                        },
                        new
                        {
                            ID_Supplier = new Guid("a251085b-5a70-4764-94f5-981e42951d84"),
                            Auto = 0,
                            ContactName = "Quinn Brown",
                            Email = "quinn.brown@gardensupplies.com",
                            Phone = "555-0119",
                            SupplierName = "Garden Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("8ee2e9b2-b343-4a62-b141-5da65066b1f0"),
                            Auto = 0,
                            ContactName = "Rachel Silver",
                            Email = "rachel.silver@digitalsolutions.com",
                            Phone = "555-0120",
                            SupplierName = "Digital Solutions"
                        });
                });

            modelBuilder.Entity("DBase.Models.Warehouse", b =>
                {
                    b.Property<Guid>("ID_Warehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ID_Warehouse");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            ID_Warehouse = new Guid("e4a36000-c5c6-4836-999b-57b3a5f5ce6c"),
                            Auto = 0,
                            Capacity = 50000,
                            Location = "Downtown",
                            ManagerName = "Alice Johnson",
                            WarehouseName = "Central Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("ac73118a-f69f-423a-aa64-f4b01dfdcafc"),
                            Auto = 0,
                            Capacity = 30000,
                            Location = "North District",
                            ManagerName = "Bob Smith",
                            WarehouseName = "Northside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("c447c363-4528-437c-ae09-41d9304e6594"),
                            Auto = 0,
                            Capacity = 40000,
                            Location = "East District",
                            ManagerName = "Charlie Brown",
                            WarehouseName = "Eastside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("25f075a3-d55d-4a93-ad67-1ec095dc4597"),
                            Auto = 0,
                            Capacity = 35000,
                            Location = "West District",
                            ManagerName = "Diana Prince",
                            WarehouseName = "Westside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("9109fa2b-a485-4f3c-b657-5271a8bea7de"),
                            Auto = 0,
                            Capacity = 4500,
                            Location = "South District",
                            ManagerName = "Ethan Hunt",
                            WarehouseName = "Southside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("12158fdf-5485-4df7-9842-3b49d240bdec"),
                            Auto = 0,
                            Capacity = 6000,
                            Location = "Industrial Park",
                            ManagerName = "Fiona Green",
                            WarehouseName = "Logistics Hub"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("cc50f20e-acbd-4667-bac5-71da8e43938e"),
                            Auto = 0,
                            Capacity = 7000,
                            Location = "Airport Road",
                            ManagerName = "George White",
                            WarehouseName = "Distribution Center"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("d014bdd3-018a-4b71-a1c1-7fb2594643de"),
                            Auto = 0,
                            Capacity = 2500,
                            Location = "Suburban Area",
                            ManagerName = "Hannah Blue",
                            WarehouseName = "Storage Facility"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("f0d04b50-203a-436f-abb2-0225b006ad16"),
                            Auto = 0,
                            Capacity = 2000,
                            Location = "Market Street",
                            ManagerName = "Ian Gray",
                            WarehouseName = "Cold Storage"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("3312aa85-d4a2-46d0-b8fc-3a504a2108e4"),
                            Auto = 0,
                            Capacity = 8000,
                            Location = "Port Area",
                            ManagerName = "Julia Red",
                            WarehouseName = "Bulk Storage"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("c774729c-690c-4c53-8468-3c73e8ffb632"),
                            Auto = 0,
                            Capacity = 1000,
                            Location = "Location A",
                            ManagerName = "Manager A",
                            WarehouseName = "Warehouse 1"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("f8f8d9e9-90e4-49ad-9336-2b2dc0fc35e3"),
                            Auto = 0,
                            Capacity = 2000,
                            Location = "Location B",
                            ManagerName = "Manager B",
                            WarehouseName = "Warehouse 2"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("b0537ac5-d718-4d97-9638-d43f7d203885"),
                            Auto = 0,
                            Capacity = 1500,
                            Location = "Location C",
                            ManagerName = "Manager C",
                            WarehouseName = "Warehouse 3"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("3232ab97-72d0-4a78-9ba9-b9a69b1d7cde"),
                            Auto = 0,
                            Capacity = 2500,
                            Location = "Location D",
                            ManagerName = "Manager D",
                            WarehouseName = "Warehouse 4"
                        });
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.HasOne("DBase.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBase.Models.OrderDetail", b =>
                {
                    b.HasOne("DBase.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBase.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.HasOne("DBase.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBase.Models.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DBase.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DBase.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DBase.Models.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
