// <auto-generated />
using System;
using DBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241122141419_RestrictOrder")]
    partial class RestrictOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBase.Models.Customer", b =>
                {
                    b.Property<Guid>("ID_Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID_Customer");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID_Customer = new Guid("01cf6e53-225e-4d97-8527-241d64096e77"),
                            Address = "123 Main St, Anytown, USA",
                            Auto = 0,
                            CustomerName = "John Doe",
                            Email = "john.doe@example.com",
                            Phone = "111-222-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("5f2462e9-827d-4331-8e9b-6adfdb0a5833"),
                            Address = "456 Elm St, Othertown, USA",
                            Auto = 0,
                            CustomerName = "Jane Smith",
                            Email = "jane.smith@example.com",
                            Phone = "444-555-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("0591e36c-5c8c-48a3-af20-77a5c58ceab8"),
                            Address = "789 Pine St, Sometown, USA",
                            Auto = 0,
                            CustomerName = "Alice Johnson",
                            Email = "alice.johnson@example.com",
                            Phone = "222-333-4444"
                        },
                        new
                        {
                            ID_Customer = new Guid("94ecb7cf-3070-4431-bb2b-1e9ae59b677a"),
                            Address = "321 Oak St, Anothertown, USA",
                            Auto = 0,
                            CustomerName = "Bob Brown",
                            Email = "bob.brown@example.com",
                            Phone = "555-666-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("05e52de3-e8d1-4def-8b3a-f73c1f8fbc16"),
                            Address = "135 Maple St, Newtown, USA",
                            Auto = 0,
                            CustomerName = "Charlie Davis",
                            Email = "charlie.davis@example.com",
                            Phone = "888-999-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("35af6d3c-5244-409e-b0d4-0f19b3a5d435"),
                            Address = "246 Cedar St, Oldtown, USA",
                            Auto = 0,
                            CustomerName = "Diana Prince",
                            Email = "diana.prince@example.com",
                            Phone = "777-888-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("8ea30d57-0684-454f-85c7-8a5050aafd0e"),
                            Address = "357 Birch St, Yourtown, USA",
                            Auto = 0,
                            CustomerName = "Ethan Hunt",
                            Email = "ethan.hunt@example.com",
                            Phone = "333-444-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("d24e3782-8e0f-4dc3-b0f3-da6785d40843"),
                            Address = "468 Spruce St, Hometown, USA",
                            Auto = 0,
                            CustomerName = "Fiona Green",
                            Email = "fiona.green@example.com",
                            Phone = "666-777-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("670c1794-dbcf-454b-a539-5d5921e19bcd"),
                            Address = "579 Fir St, Thistown, USA",
                            Auto = 0,
                            CustomerName = "George White",
                            Email = "george.white@example.com",
                            Phone = "999-000-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("54e8d890-f148-4d22-9eab-29c3d7e017ce"),
                            Address = "680 Willow St, Thatown, USA",
                            Auto = 0,
                            CustomerName = "Hannah Blue",
                            Email = "hannah.blue@example.com",
                            Phone = "222-111-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("d0d88b30-1b63-42af-a902-de0c85468a85"),
                            Address = "791 Ash St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Ian Gray",
                            Email = "ian.gray@example.com",
                            Phone = "444-222-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("345bc33a-4577-4b0d-b78e-b1bc3112ddb7"),
                            Address = "802 Cherry St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Julia Red",
                            Email = "julia.red@example.com",
                            Phone = "555-333-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("07f4b0f9-0109-44e4-98e7-f9305afe2680"),
                            Address = "913 Peach St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Kevin Black",
                            Email = "kevin.black@example.com",
                            Phone = "666-444-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("38d16c73-a500-4402-a854-96f2245d5df2"),
                            Address = "024 Plum St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Laura Pink",
                            Email = "laura.pink@example.com",
                            Phone = "777-555-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("8fa5437e-c656-4dba-85f0-26c7115afe54"),
                            Address = "135 Lemon St, Oldcity, USA",
                            Auto = 0,
                            CustomerName = "Mike Yellow",
                            Email = "mike.yellow@example.com",
                            Phone = "888-666-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("431a2ef2-59de-4540-bd52-5e1c90cc6183"),
                            Address = "246 Lime St, Yourcity, USA",
                            Auto = 0,
                            CustomerName = "Nina Cyan",
                            Email = "nina.cyan@example.com",
                            Phone = "999-777-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("491003a8-8603-402b-9636-66b81884ca02"),
                            Address = "357 Grape St, Thatcity, USA",
                            Auto = 0,
                            CustomerName = "Oscar Magenta",
                            Email = "oscar.magenta@example.com",
                            Phone = "000-888-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("2738e822-164a-42df-8be2-41a8ad0bb17d"),
                            Address = "468 Berry St, Thiscity, USA",
                            Auto = 0,
                            CustomerName = "Paula Teal",
                            Email = "paula.teal@example.com",
                            Phone = "111-999-2222"
                        },
                        new
                        {
                            ID_Customer = new Guid("c8aaaafd-5ff1-488c-be22-3915564fb7c2"),
                            Address = "579 Fig St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Quinn Brown",
                            Email = "quinn.brown@example.com",
                            Phone = "222-000-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("1420dd59-c914-4806-aff4-4d8e66cc5c33"),
                            Address = "680 Date St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Rachel Silver",
                            Email = "rachel.silver@example.com",
                            Phone = "333-111-4444"
                        },
                        new
                        {
                            ID_Customer = new Guid("ff382f41-ca4b-4398-8e38-c521cef28455"),
                            Address = "791 Olive St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Steve Gold",
                            Email = "steve.gold@example.com",
                            Phone = "444-222-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("8a81746a-65bc-42e3-9503-5c0cf2aa3bd3"),
                            Address = "802 Walnut St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Tina Copper",
                            Email = "tina.copper@example.com",
                            Phone = "555-333-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("1411103b-91b0-4c1c-b787-66c17b54fd4f"),
                            Address = "913 Chestnut St, Oldcity, USA",
                            Auto = 0,
                            CustomerName = "Ursula Bronze",
                            Email = "ursula.bronze@example.com",
                            Phone = "666-444-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("2fc6ca95-0c55-4964-b962-7724d5ea2040"),
                            Address = "024 Maple St, Yourcity, USA",
                            Auto = 0,
                            CustomerName = "Victor Steel",
                            Email = "victor.steel@example.com",
                            Phone = "777-555-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("475e350c-7567-4515-abb3-fd9a0ebf1280"),
                            Address = "135 Pineapple St, Thatcity, USA",
                            Auto = 0,
                            CustomerName = "Wendy Iron",
                            Email = "wendy.iron@example.com",
                            Phone = "888-666-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("1a62b98a-9122-46cb-b4e2-d805876c19d2"),
                            Address = "246 Coconut St, Thiscity, USA",
                            Auto = 0,
                            CustomerName = "Xander Zinc",
                            Email = "xander.zinc@example.com",
                            Phone = "999-777-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("6f3ffbc6-1334-445e-ac9c-0da0fa449f10"),
                            Address = "357 Papaya St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Yvonne Nickel",
                            Email = "yvonne.nickel@example.com",
                            Phone = "000-888-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("b6e81c51-fcf4-4d4b-a94d-0a3f24b0ff22"),
                            Address = "680 Kiwi St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Zachary Lead",
                            Email = "zachary.lead@example.com",
                            Phone = "111-999-2222"
                        },
                        new
                        {
                            ID_Customer = new Guid("878251d8-97dc-4912-a0e0-85be7b4fbf22"),
                            Address = "791 Mango St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Alice Cooper",
                            Email = "alice.cooper@example.com",
                            Phone = "222-000-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("4f9826c7-7a7f-4786-a469-f0a82e63991a"),
                            Address = "802 Banana St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Bob Marley",
                            Email = "bob.marley@example.com",
                            Phone = "333-111-4444"
                        });
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.Property<Guid>("ID_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Order");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID_Order = new Guid("5c7b2551-5591-4c4a-9f95-42c83924b3f1"),
                            Auto = 0,
                            CustomerID = new Guid("01cf6e53-225e-4d97-8527-241d64096e77"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3270),
                            Status = "Completed",
                            TotalAmount = 35.00m
                        },
                        new
                        {
                            ID_Order = new Guid("89f1b8dc-8083-4a0d-b5cd-d592be9cea76"),
                            Auto = 0,
                            CustomerID = new Guid("5f2462e9-827d-4331-8e9b-6adfdb0a5833"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3285),
                            Status = "Pending",
                            TotalAmount = 20.00m
                        },
                        new
                        {
                            ID_Order = new Guid("108c73fe-ef1b-4b49-808c-94d025da79e5"),
                            Auto = 0,
                            CustomerID = new Guid("0591e36c-5c8c-48a3-af20-77a5c58ceab8"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3289),
                            Status = "Completed",
                            TotalAmount = 80.00m
                        },
                        new
                        {
                            ID_Order = new Guid("fb46131e-77d7-4e26-b059-aaabeae8d536"),
                            Auto = 0,
                            CustomerID = new Guid("94ecb7cf-3070-4431-bb2b-1e9ae59b677a"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3293),
                            Status = "Shipped",
                            TotalAmount = 70.00m
                        },
                        new
                        {
                            ID_Order = new Guid("3a90befc-db71-4b9b-a153-577da2accbf6"),
                            Auto = 0,
                            CustomerID = new Guid("05e52de3-e8d1-4def-8b3a-f73c1f8fbc16"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3297),
                            Status = "Completed",
                            TotalAmount = 300.50m
                        },
                        new
                        {
                            ID_Order = new Guid("dde98dd8-ba50-4cf3-9608-7c9d907ab22e"),
                            Auto = 0,
                            CustomerID = new Guid("35af6d3c-5244-409e-b0d4-0f19b3a5d435"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3301),
                            Status = "Pending",
                            TotalAmount = 300.50m
                        },
                        new
                        {
                            ID_Order = new Guid("037fd886-5a76-4239-8533-3b22a792932f"),
                            Auto = 0,
                            CustomerID = new Guid("8ea30d57-0684-454f-85c7-8a5050aafd0e"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3305),
                            Status = "Shipped",
                            TotalAmount = 6000.50m
                        },
                        new
                        {
                            ID_Order = new Guid("6aeefae0-0f8e-4793-99b5-fe61522429fd"),
                            Auto = 0,
                            CustomerID = new Guid("d24e3782-8e0f-4dc3-b0f3-da6785d40843"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3309),
                            Status = "Completed",
                            TotalAmount = 5001.30m
                        },
                        new
                        {
                            ID_Order = new Guid("7c2aa6f4-0e26-4f20-b14e-b1e5fdcaddca"),
                            Auto = 0,
                            CustomerID = new Guid("670c1794-dbcf-454b-a539-5d5921e19bcd"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3313),
                            Status = "Pending",
                            TotalAmount = 1100.20m
                        },
                        new
                        {
                            ID_Order = new Guid("04cb98fe-49ff-4c59-810e-5c1d6751fa2f"),
                            Auto = 0,
                            CustomerID = new Guid("54e8d890-f148-4d22-9eab-29c3d7e017ce"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3321),
                            Status = "Completed",
                            TotalAmount = 3500.00m
                        },
                        new
                        {
                            ID_Order = new Guid("1457d5bc-0753-431b-b18c-133d41b2744b"),
                            Auto = 0,
                            CustomerID = new Guid("d0d88b30-1b63-42af-a902-de0c85468a85"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3325),
                            Status = "Pending",
                            TotalAmount = 800.00m
                        },
                        new
                        {
                            ID_Order = new Guid("f235b7ac-c009-4fdd-9d45-e8e58602aaca"),
                            Auto = 0,
                            CustomerID = new Guid("345bc33a-4577-4b0d-b78e-b1bc3112ddb7"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3329),
                            Status = "Shipped",
                            TotalAmount = 1400.20m
                        },
                        new
                        {
                            ID_Order = new Guid("5e8217be-12dc-4fd4-940d-7f9a064f9882"),
                            Auto = 0,
                            CustomerID = new Guid("07f4b0f9-0109-44e4-98e7-f9305afe2680"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3333),
                            Status = "Completed",
                            TotalAmount = 3201.00m
                        },
                        new
                        {
                            ID_Order = new Guid("0dca7f0a-7e5b-4449-808d-a59a79dae0f5"),
                            Auto = 0,
                            CustomerID = new Guid("38d16c73-a500-4402-a854-96f2245d5df2"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 14, 18, 861, DateTimeKind.Utc).AddTicks(3337),
                            Status = "Pending",
                            TotalAmount = 6300.80m
                        });
                });

            modelBuilder.Entity("DBase.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("ID_OrderDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ID_OrderDetails");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            ID_OrderDetails = new Guid("864fdd56-6a0e-454d-8dd9-3309164482db"),
                            Auto = 0,
                            OrderId = new Guid("5c7b2551-5591-4c4a-9f95-42c83924b3f1"),
                            ProductId = new Guid("ca83b676-760d-4416-a308-0dcd22323870"),
                            Quantity = 2,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("a72788f8-52bc-4eab-b156-0ecf1ca2993e"),
                            Auto = 0,
                            OrderId = new Guid("5c7b2551-5591-4c4a-9f95-42c83924b3f1"),
                            ProductId = new Guid("6e79c779-d656-4c20-9be5-fddf4821a170"),
                            Quantity = 1,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("e82819d7-8838-411d-8aee-3f4f27a51f21"),
                            Auto = 0,
                            OrderId = new Guid("89f1b8dc-8083-4a0d-b5cd-d592be9cea76"),
                            ProductId = new Guid("36298747-c223-42da-99c7-803effd46d99"),
                            Quantity = 1,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("24b903b1-5dec-4707-9797-f3516c798913"),
                            Auto = 0,
                            OrderId = new Guid("108c73fe-ef1b-4b49-808c-94d025da79e5"),
                            ProductId = new Guid("3334d44a-6caa-48ea-8ca4-1222cd4b245e"),
                            Quantity = 2,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("f7fe09c2-9a5c-4ef2-9e04-d00a724d5c3d"),
                            Auto = 0,
                            OrderId = new Guid("108c73fe-ef1b-4b49-808c-94d025da79e5"),
                            ProductId = new Guid("2ebcd021-bb15-4a6e-907f-04f14e38d8ad"),
                            Quantity = 1,
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("d455eb8c-7bf9-4d1c-9e22-da32896e9e46"),
                            Auto = 0,
                            OrderId = new Guid("fb46131e-77d7-4e26-b059-aaabeae8d536"),
                            ProductId = new Guid("e6d5cc8f-9799-49ca-8f62-e86d1064c021"),
                            Quantity = 2,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("49740892-6e8d-45bf-8c5d-7cd4e9eb4de2"),
                            Auto = 0,
                            OrderId = new Guid("3a90befc-db71-4b9b-a153-577da2accbf6"),
                            ProductId = new Guid("2dcecc62-ca85-40b5-a28f-95b0d8272087"),
                            Quantity = 1,
                            UnitPrice = 100.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("4692aa1f-84d2-4ee9-9bf0-b3ddf28b25b5"),
                            Auto = 0,
                            OrderId = new Guid("3a90befc-db71-4b9b-a153-577da2accbf6"),
                            ProductId = new Guid("27aa32c9-8ab2-4487-9512-59f09eabe58b"),
                            Quantity = 1,
                            UnitPrice = 200.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("96d2879a-cd55-4600-b07a-098040df2c27"),
                            Auto = 0,
                            OrderId = new Guid("dde98dd8-ba50-4cf3-9608-7c9d907ab22e"),
                            ProductId = new Guid("6b2c275c-e851-48b1-9efc-94e93f165466"),
                            Quantity = 1,
                            UnitPrice = 300.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("f924aa36-5720-4668-ba5f-332ab13ff1bf"),
                            Auto = 0,
                            OrderId = new Guid("037fd886-5a76-4239-8533-3b22a792932f"),
                            ProductId = new Guid("9480b47d-dffc-4ab2-abcf-6a6dc7f8c0ba"),
                            Quantity = 1,
                            UnitPrice = 4000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("70bf833e-99b7-4e02-a536-7aa7dccfe251"),
                            Auto = 0,
                            OrderId = new Guid("037fd886-5a76-4239-8533-3b22a792932f"),
                            ProductId = new Guid("fd672b8b-07df-4ec6-a57b-b43d78ea1534"),
                            Quantity = 1,
                            UnitPrice = 2000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("752a9026-8083-4d8f-8e49-6fda2b99ddea"),
                            Auto = 0,
                            OrderId = new Guid("6aeefae0-0f8e-4793-99b5-fe61522429fd"),
                            ProductId = new Guid("bd26ad66-0697-43df-9730-49858e2e0beb"),
                            Quantity = 1,
                            UnitPrice = 1000.80m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("54631b53-9904-432b-a931-76ce72633618"),
                            Auto = 0,
                            OrderId = new Guid("6aeefae0-0f8e-4793-99b5-fe61522429fd"),
                            ProductId = new Guid("1f8bee0b-a286-4e8d-9bcf-7928b96cd4d6"),
                            Quantity = 1,
                            UnitPrice = 4000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("4a7adb25-0feb-4ffc-9615-12fed08f1228"),
                            Auto = 0,
                            OrderId = new Guid("7c2aa6f4-0e26-4f20-b14e-b1e5fdcaddca"),
                            ProductId = new Guid("3b3ddcb9-7488-4676-91dc-a23de8bba02c"),
                            Quantity = 1,
                            UnitPrice = 6000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("37e0ee70-e3db-4e61-b411-2789a549dceb"),
                            Auto = 0,
                            OrderId = new Guid("7c2aa6f4-0e26-4f20-b14e-b1e5fdcaddca"),
                            ProductId = new Guid("ca137355-72a2-42de-b91a-539a14bc1198"),
                            Quantity = 1,
                            UnitPrice = 3000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("aded7c5b-d160-4a0d-b46f-1cc7db7911b2"),
                            Auto = 0,
                            OrderId = new Guid("7c2aa6f4-0e26-4f20-b14e-b1e5fdcaddca"),
                            ProductId = new Guid("862d502b-3e00-4d1a-998f-8b3c179ccf01"),
                            Quantity = 1,
                            UnitPrice = 2000.20m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("47206b95-92a4-4017-8705-d7bc7e1a2973"),
                            Auto = 0,
                            OrderId = new Guid("04cb98fe-49ff-4c59-810e-5c1d6751fa2f"),
                            ProductId = new Guid("2b1ef509-e614-40e4-a635-07f2c8d80026"),
                            Quantity = 1,
                            UnitPrice = 3000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("1eecdebc-d76d-4f12-8d08-a5022cb2a89f"),
                            Auto = 0,
                            OrderId = new Guid("04cb98fe-49ff-4c59-810e-5c1d6751fa2f"),
                            ProductId = new Guid("a2096caa-4059-4eba-ad4d-c41456b56e52"),
                            Quantity = 1,
                            UnitPrice = 500.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("de2e29b5-95e7-41cf-ac26-30535a27e0eb"),
                            Auto = 0,
                            OrderId = new Guid("1457d5bc-0753-431b-b18c-133d41b2744b"),
                            ProductId = new Guid("7dc1ac21-5a81-4d58-9140-5acae67137a1"),
                            Quantity = 1,
                            UnitPrice = 800.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("60866448-b428-4a69-ae5f-74fd6f3f4494"),
                            Auto = 0,
                            OrderId = new Guid("f235b7ac-c009-4fdd-9d45-e8e58602aaca"),
                            ProductId = new Guid("b0feacec-c662-41c2-94f1-2ca100f08333"),
                            Quantity = 1,
                            UnitPrice = 1000.20m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("3e5d419a-e163-4875-8bc2-a2d785a0c2df"),
                            Auto = 0,
                            OrderId = new Guid("f235b7ac-c009-4fdd-9d45-e8e58602aaca"),
                            ProductId = new Guid("755911b1-7e91-4c7c-8539-d6eb7a3cd395"),
                            Quantity = 1,
                            UnitPrice = 400.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("2a7e56a5-884c-4098-b798-a5c90d3c11c6"),
                            Auto = 0,
                            OrderId = new Guid("5e8217be-12dc-4fd4-940d-7f9a064f9882"),
                            ProductId = new Guid("047a9786-cc61-4100-b23b-37649f6adb75"),
                            Quantity = 1,
                            UnitPrice = 3000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("8b79d2e4-891e-4d73-8f02-375b8b14c3db"),
                            Auto = 0,
                            OrderId = new Guid("5e8217be-12dc-4fd4-940d-7f9a064f9882"),
                            ProductId = new Guid("fa5f7e33-1935-45a0-9684-24f9466da4e5"),
                            Quantity = 1,
                            UnitPrice = 200.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("7a4e44bb-65a9-4908-b641-c13d61ea626b"),
                            Auto = 0,
                            OrderId = new Guid("0dca7f0a-7e5b-4449-808d-a59a79dae0f5"),
                            ProductId = new Guid("e0423371-2973-411d-aa0b-9166c2613577"),
                            Quantity = 1,
                            UnitPrice = 100.80m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("1d9400cc-32e9-48ac-961a-2e26e83039ec"),
                            Auto = 0,
                            OrderId = new Guid("0dca7f0a-7e5b-4449-808d-a59a79dae0f5"),
                            ProductId = new Guid("33a8587b-b03f-4daa-8dec-68d94f86d2c7"),
                            Quantity = 1,
                            UnitPrice = 200.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("6b81ec45-4890-4332-8df0-1e3f55d5e5d4"),
                            Auto = 0,
                            OrderId = new Guid("0dca7f0a-7e5b-4449-808d-a59a79dae0f5"),
                            ProductId = new Guid("308a3607-1463-497c-a673-88614fc90078"),
                            Quantity = 1,
                            UnitPrice = 6000.00m
                        });
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.Property<Guid>("ID_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("Cell")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Producer")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WarehouseID")
                        .HasColumnType("uuid");

                    b.HasKey("ID_Product");

                    b.HasIndex("SupplierID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID_Product = new Guid("ca83b676-760d-4416-a308-0dcd22323870"),
                            Auto = 0,
                            Cell = "a100",
                            Producer = "Producer 1",
                            ProductName = "Product 1",
                            QuantityInStock = 100,
                            SupplierID = new Guid("fb0fc0b4-f311-4bcb-ad20-b838b1ad1920"),
                            UnitPrice = 10.00m,
                            WarehouseID = new Guid("7c9914ff-256d-4beb-9ef8-c6eebaf1760e")
                        },
                        new
                        {
                            ID_Product = new Guid("6e79c779-d656-4c20-9be5-fddf4821a170"),
                            Auto = 0,
                            Cell = "a101",
                            Producer = "Producer 2",
                            ProductName = "Product 2",
                            QuantityInStock = 200,
                            SupplierID = new Guid("fb0fc0b4-f311-4bcb-ad20-b838b1ad1920"),
                            UnitPrice = 15.00m,
                            WarehouseID = new Guid("7c9914ff-256d-4beb-9ef8-c6eebaf1760e")
                        },
                        new
                        {
                            ID_Product = new Guid("36298747-c223-42da-99c7-803effd46d99"),
                            Auto = 0,
                            Cell = "a102",
                            Producer = "Producer 2",
                            ProductName = "Product 3",
                            QuantityInStock = 150,
                            SupplierID = new Guid("315e9973-c145-4bfd-985e-6a04aad99aeb"),
                            UnitPrice = 20.00m,
                            WarehouseID = new Guid("c3fb3a21-ca5d-47e0-b5f6-1f3556cd01b3")
                        },
                        new
                        {
                            ID_Product = new Guid("3334d44a-6caa-48ea-8ca4-1222cd4b245e"),
                            Auto = 0,
                            Cell = "a103",
                            Producer = "Producer 2",
                            ProductName = "Product 4",
                            QuantityInStock = 80,
                            SupplierID = new Guid("89148db9-f165-4cb6-90f9-eb1a7b4e58e6"),
                            UnitPrice = 25.00m,
                            WarehouseID = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42")
                        },
                        new
                        {
                            ID_Product = new Guid("2ebcd021-bb15-4a6e-907f-04f14e38d8ad"),
                            Auto = 0,
                            Cell = "a104",
                            Producer = "Producer 3",
                            ProductName = "Product 5",
                            QuantityInStock = 60,
                            SupplierID = new Guid("89148db9-f165-4cb6-90f9-eb1a7b4e58e6"),
                            UnitPrice = 30.00m,
                            WarehouseID = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42")
                        },
                        new
                        {
                            ID_Product = new Guid("e6d5cc8f-9799-49ca-8f62-e86d1064c021"),
                            Auto = 0,
                            Cell = "a105",
                            Producer = "Producer 3",
                            ProductName = "Product 6",
                            QuantityInStock = 40,
                            SupplierID = new Guid("33b3d61a-77dc-4090-8f7c-858b8c8691cd"),
                            UnitPrice = 35.00m,
                            WarehouseID = new Guid("79620bb0-fec4-4921-9b55-c3d1d9da57cc")
                        },
                        new
                        {
                            ID_Product = new Guid("2dcecc62-ca85-40b5-a28f-95b0d8272087"),
                            Auto = 0,
                            Cell = "a10",
                            Producer = "Fresh Farms",
                            ProductName = "Organic Apples",
                            QuantityInStock = 150,
                            SupplierID = new Guid("00ec677e-f5d9-45bc-8f2e-df7d906b8921"),
                            UnitPrice = 100.50m,
                            WarehouseID = new Guid("dc7eeb83-ee94-44fe-93eb-da812056e029")
                        },
                        new
                        {
                            ID_Product = new Guid("27aa32c9-8ab2-4487-9512-59f09eabe58b"),
                            Auto = 0,
                            Cell = "a11",
                            Producer = "Bakery Co.",
                            ProductName = "Whole Wheat Bread",
                            QuantityInStock = 200,
                            SupplierID = new Guid("00ec677e-f5d9-45bc-8f2e-df7d906b8921"),
                            UnitPrice = 200.00m,
                            WarehouseID = new Guid("dc7eeb83-ee94-44fe-93eb-da812056e029")
                        },
                        new
                        {
                            ID_Product = new Guid("6b2c275c-e851-48b1-9efc-94e93f165466"),
                            Auto = 0,
                            Cell = "a12",
                            Producer = "Nutty Delights",
                            ProductName = "Almond Milk",
                            QuantityInStock = 100,
                            SupplierID = new Guid("ba329989-ac8c-4044-9a7d-b7566f0355c1"),
                            UnitPrice = 300.50m,
                            WarehouseID = new Guid("ea734f6f-b128-4202-9f81-337a0bf64783")
                        },
                        new
                        {
                            ID_Product = new Guid("9480b47d-dffc-4ab2-abcf-6a6dc7f8c0ba"),
                            Auto = 0,
                            Cell = "a13",
                            Producer = "Dairy Best",
                            ProductName = "Greek Yogurt",
                            QuantityInStock = 80,
                            SupplierID = new Guid("ba329989-ac8c-4044-9a7d-b7566f0355c1"),
                            UnitPrice = 4000.00m,
                            WarehouseID = new Guid("3b4ed331-9392-4d7c-bf65-56a315c6efac")
                        },
                        new
                        {
                            ID_Product = new Guid("fd672b8b-07df-4ec6-a57b-b43d78ea1534"),
                            Auto = 0,
                            Cell = "a14",
                            Producer = "Farm Fresh",
                            ProductName = "Free-Range Eggs",
                            QuantityInStock = 60,
                            SupplierID = new Guid("ba329989-ac8c-4044-9a7d-b7566f0355c1"),
                            UnitPrice = 2000.50m,
                            WarehouseID = new Guid("3b4ed331-9392-4d7c-bf65-56a315c6efac")
                        },
                        new
                        {
                            ID_Product = new Guid("bd26ad66-0697-43df-9730-49858e2e0beb"),
                            Auto = 0,
                            Cell = "a15",
                            Producer = "Grain Masters",
                            ProductName = "Brown Rice",
                            QuantityInStock = 120,
                            SupplierID = new Guid("33bd5409-2f0e-4d59-b21c-c4a9685b4ea0"),
                            UnitPrice = 1000.80m,
                            WarehouseID = new Guid("fca5864c-4e08-453e-979d-dc28807d2842")
                        },
                        new
                        {
                            ID_Product = new Guid("1f8bee0b-a286-4e8d-9bcf-7928b96cd4d6"),
                            Auto = 0,
                            Cell = "a106",
                            Producer = "Healthy Grains",
                            ProductName = "Quinoa",
                            QuantityInStock = 90,
                            SupplierID = new Guid("33bd5409-2f0e-4d59-b21c-c4a9685b4ea0"),
                            UnitPrice = 4000.50m,
                            WarehouseID = new Guid("fca5864c-4e08-453e-979d-dc28807d2842")
                        },
                        new
                        {
                            ID_Product = new Guid("3b3ddcb9-7488-4676-91dc-a23de8bba02c"),
                            Auto = 0,
                            Cell = "a107",
                            Producer = "Tropical Goods",
                            ProductName = "Coconut Oil",
                            QuantityInStock = 70,
                            SupplierID = new Guid("33bd5409-2f0e-4d59-b21c-c4a9685b4ea0"),
                            UnitPrice = 6000.00m,
                            WarehouseID = new Guid("ea734f6f-b128-4202-9f81-337a0bf64783")
                        },
                        new
                        {
                            ID_Product = new Guid("ca137355-72a2-42de-b91a-539a14bc1198"),
                            Auto = 0,
                            Cell = "a108",
                            Producer = "Choco Bliss",
                            ProductName = "Dark Chocolate",
                            QuantityInStock = 50,
                            SupplierID = new Guid("c82e5c62-ea18-4c29-93dc-28b309561404"),
                            UnitPrice = 3000.00m,
                            WarehouseID = new Guid("839b4827-3e7f-4c35-9d2e-6e6501ac4f8e")
                        },
                        new
                        {
                            ID_Product = new Guid("862d502b-3e00-4d1a-998f-8b3c179ccf01"),
                            Auto = 0,
                            Cell = "a109",
                            Producer = "Green Leaf",
                            ProductName = "Spinach",
                            QuantityInStock = 110,
                            SupplierID = new Guid("3d5eb318-3442-4200-9ed7-7cb267c816fd"),
                            UnitPrice = 2000.20m,
                            WarehouseID = new Guid("6b901674-76cd-4aca-8e3c-1d19c2732341")
                        },
                        new
                        {
                            ID_Product = new Guid("2b1ef509-e614-40e4-a635-07f2c8d80026"),
                            Auto = 0,
                            Cell = "a110",
                            Producer = "Healthy Mornings",
                            ProductName = "Oatmeal",
                            QuantityInStock = 200,
                            SupplierID = new Guid("39daa169-047e-4184-bd37-15f04b127175"),
                            UnitPrice = 3000.00m,
                            WarehouseID = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42")
                        },
                        new
                        {
                            ID_Product = new Guid("a2096caa-4059-4eba-ad4d-c41456b56e52"),
                            Auto = 0,
                            Cell = "a111",
                            Producer = "Superfoods Co.",
                            ProductName = "Chia Seeds",
                            QuantityInStock = 150,
                            SupplierID = new Guid("14fbefad-8f63-430f-82d0-c10d28f7862a"),
                            UnitPrice = 500.00m,
                            WarehouseID = new Guid("4f5e5098-3074-4dde-94cf-90ef7a2b56c3")
                        },
                        new
                        {
                            ID_Product = new Guid("7dc1ac21-5a81-4d58-9140-5acae67137a1"),
                            Auto = 0,
                            Cell = "a112",
                            Producer = "Nature's Best",
                            ProductName = "Avocado Oil",
                            QuantityInStock = 80,
                            SupplierID = new Guid("d97d0cf9-9dd0-433a-9c98-08b75063a346"),
                            UnitPrice = 800.00m,
                            WarehouseID = new Guid("3b4ed331-9392-4d7c-bf65-56a315c6efac")
                        },
                        new
                        {
                            ID_Product = new Guid("b0feacec-c662-41c2-94f1-2ca100f08333"),
                            Auto = 0,
                            Cell = "a113",
                            Producer = "Legume Lovers",
                            ProductName = "Canned Chickpeas",
                            QuantityInStock = 300,
                            SupplierID = new Guid("b7a01094-3afb-4e13-818a-59a931c2f48b"),
                            UnitPrice = 1000.20m,
                            WarehouseID = new Guid("fca5864c-4e08-453e-979d-dc28807d2842")
                        },
                        new
                        {
                            ID_Product = new Guid("755911b1-7e91-4c7c-8539-d6eb7a3cd395"),
                            Auto = 0,
                            Cell = "a114",
                            Producer = "Berry Good",
                            ProductName = "Frozen Berries",
                            QuantityInStock = 120,
                            SupplierID = new Guid("0857631e-4fce-4a52-b717-75c195dc1881"),
                            UnitPrice = 400.00m,
                            WarehouseID = new Guid("ea734f6f-b128-4202-9f81-337a0bf64783")
                        },
                        new
                        {
                            ID_Product = new Guid("047a9786-cc61-4100-b23b-37649f6adb75"),
                            Auto = 0,
                            Cell = "a115",
                            Producer = "Nutty Spread",
                            ProductName = "Peanut Butter",
                            QuantityInStock = 90,
                            SupplierID = new Guid("7ddd3d5b-3bf3-41ea-a1de-e3f304ddfeea"),
                            UnitPrice = 3000.50m,
                            WarehouseID = new Guid("16274e2c-83ef-4ddd-b504-18a637e94a66")
                        },
                        new
                        {
                            ID_Product = new Guid("fa5f7e33-1935-45a0-9684-24f9466da4e5"),
                            Auto = 0,
                            Cell = "a116",
                            Producer = "Tropical Refreshments",
                            ProductName = "Coconut Water",
                            QuantityInStock = 200,
                            SupplierID = new Guid("5a2d932c-6505-451f-877f-6be7273bb271"),
                            UnitPrice = 200.50m,
                            WarehouseID = new Guid("42bf36ef-7634-4ba8-8be5-b8a171ddab12")
                        },
                        new
                        {
                            ID_Product = new Guid("e0423371-2973-411d-aa0b-9166c2613577"),
                            Auto = 0,
                            Cell = "a117",
                            Producer = "Snack Time",
                            ProductName = "Granola Bars",
                            QuantityInStock = 150,
                            SupplierID = new Guid("7bb086a8-c6d7-48c2-9e13-d8b3316a0421"),
                            UnitPrice = 100.80m,
                            WarehouseID = new Guid("839b4827-3e7f-4c35-9d2e-6e6501ac4f8e")
                        },
                        new
                        {
                            ID_Product = new Guid("33a8587b-b03f-4daa-8dec-68d94f86d2c7"),
                            Auto = 0,
                            Cell = "a118",
                            Producer = "Dips & Spreads",
                            ProductName = "Hummus",
                            QuantityInStock = 100,
                            SupplierID = new Guid("f0566ed2-52ef-4ddc-9161-26bcb73b60bd"),
                            UnitPrice = 200.00m,
                            WarehouseID = new Guid("6b901674-76cd-4aca-8e3c-1d19c2732341")
                        },
                        new
                        {
                            ID_Product = new Guid("308a3607-1463-497c-a673-88614fc90078"),
                            Auto = 0,
                            Cell = "a119",
                            Producer = "Sweet Harvest",
                            ProductName = "Maple Syrup",
                            QuantityInStock = 70,
                            SupplierID = new Guid("71466897-d17c-49d1-9d9f-d8eb8670fd9c"),
                            UnitPrice = 6000.00m,
                            WarehouseID = new Guid("67ab8e0f-fad1-4515-95a6-9114c3aeb382")
                        },
                        new
                        {
                            ID_Product = new Guid("71430cea-5a57-4d87-a865-cfde3e2f6829"),
                            Auto = 0,
                            Cell = "a126",
                            Producer = "Root Veggies",
                            ProductName = "Sweet Potatoes",
                            QuantityInStock = 120,
                            SupplierID = new Guid("89148db9-f165-4cb6-90f9-eb1a7b4e58e6"),
                            UnitPrice = 100.80m,
                            WarehouseID = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42")
                        },
                        new
                        {
                            ID_Product = new Guid("c151326f-3730-4cbc-9dd6-4b9b7766ccc9"),
                            Auto = 0,
                            Cell = "a127",
                            Producer = "Garden Fresh",
                            ProductName = "Canned Tomatoes",
                            QuantityInStock = 300,
                            SupplierID = new Guid("33b3d61a-77dc-4090-8f7c-858b8c8691cd"),
                            UnitPrice = 1000.00m,
                            WarehouseID = new Guid("79620bb0-fec4-4921-9b55-c3d1d9da57cc")
                        },
                        new
                        {
                            ID_Product = new Guid("2ca7a9db-c84a-4036-bde9-68d1bb1d38cf"),
                            Auto = 0,
                            Cell = "a128",
                            Producer = "Healthy Snacks",
                            ProductName = "Nut Mix",
                            QuantityInStock = 90,
                            SupplierID = new Guid("315e9973-c145-4bfd-985e-6a04aad99aeb"),
                            UnitPrice = 600.00m,
                            WarehouseID = new Guid("c3fb3a21-ca5d-47e0-b5f6-1f3556cd01b3")
                        },
                        new
                        {
                            ID_Product = new Guid("5292c381-750d-4213-a9aa-730f09a95305"),
                            Auto = 0,
                            Cell = "a129",
                            Producer = "Gourmet Essentials",
                            ProductName = "Balsamic Vinegar",
                            QuantityInStock = 70,
                            SupplierID = new Guid("fb0fc0b4-f311-4bcb-ad20-b838b1ad1920"),
                            UnitPrice = 4000.50m,
                            WarehouseID = new Guid("7c9914ff-256d-4beb-9ef8-c6eebaf1760e")
                        },
                        new
                        {
                            ID_Product = new Guid("1d40e538-8733-484e-ae46-598c6d83e211"),
                            Auto = 0,
                            Cell = "a130",
                            Producer = "Plant Protein Co.",
                            ProductName = "Tofu",
                            QuantityInStock = 100,
                            SupplierID = new Guid("71466897-d17c-49d1-9d9f-d8eb8670fd9c"),
                            UnitPrice = 200.50m,
                            WarehouseID = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42")
                        },
                        new
                        {
                            ID_Product = new Guid("1e2d7f43-aa9f-4d98-aae6-c7b0a86d611c"),
                            Auto = 0,
                            Cell = "a131",
                            Producer = "Nutty Delights",
                            ProductName = "Almonds",
                            QuantityInStock = 80,
                            SupplierID = new Guid("f0566ed2-52ef-4ddc-9161-26bcb73b60bd"),
                            UnitPrice = 8000.00m,
                            WarehouseID = new Guid("79620bb0-fec4-4921-9b55-c3d1d9da57cc")
                        },
                        new
                        {
                            ID_Product = new Guid("803f1b7a-6108-4c01-86ba-5b7ce183bd51"),
                            Auto = 0,
                            Cell = "a132",
                            Producer = "Spice World",
                            ProductName = "Cinnamon",
                            QuantityInStock = 150,
                            SupplierID = new Guid("7bb086a8-c6d7-48c2-9e13-d8b3316a0421"),
                            UnitPrice = 300.00m,
                            WarehouseID = new Guid("7c9914ff-256d-4beb-9ef8-c6eebaf1760e")
                        },
                        new
                        {
                            ID_Product = new Guid("f0bcffd8-2ccc-4969-bab9-69ee81d4a2d1"),
                            Auto = 0,
                            Cell = "a133",
                            Producer = "Legume Lovers",
                            ProductName = "Black Beans",
                            QuantityInStock = 200,
                            SupplierID = new Guid("22f8cce8-dad5-4d31-a827-35b2790c7348"),
                            UnitPrice = 100.50m,
                            WarehouseID = new Guid("c3fb3a21-ca5d-47e0-b5f6-1f3556cd01b3")
                        },
                        new
                        {
                            ID_Product = new Guid("c105ae86-9dbe-4331-9665-0afe4fb881e3"),
                            Auto = 0,
                            Cell = "a134",
                            Producer = "Fresh Greens",
                            ProductName = "Cabbage",
                            QuantityInStock = 120,
                            SupplierID = new Guid("825256d5-a3d1-4985-af2d-aa01389b9dd7"),
                            UnitPrice = 166.80m,
                            WarehouseID = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42")
                        },
                        new
                        {
                            ID_Product = new Guid("20b7970e-3cd5-4bcd-9eb3-3e6d9083460a"),
                            Auto = 0,
                            Cell = "a135",
                            Producer = "Healthy Harvest",
                            ProductName = "Lentils",
                            QuantityInStock = 180,
                            SupplierID = new Guid("00ec677e-f5d9-45bc-8f2e-df7d906b8921"),
                            UnitPrice = 177.20m,
                            WarehouseID = new Guid("79620bb0-fec4-4921-9b55-c3d1d9da57cc")
                        },
                        new
                        {
                            ID_Product = new Guid("0b85f7c4-10c4-48b7-8e33-b2bcc6c930e0"),
                            Auto = 0,
                            Cell = "a136",
                            Producer = "Snack Time",
                            ProductName = "Pumpkin Seeds",
                            QuantityInStock = 90,
                            SupplierID = new Guid("ba329989-ac8c-4044-9a7d-b7566f0355c1"),
                            UnitPrice = 4777.00m,
                            WarehouseID = new Guid("7c9914ff-256d-4beb-9ef8-c6eebaf1760e")
                        },
                        new
                        {
                            ID_Product = new Guid("98d5875b-a87a-441a-9349-6d0fa15569da"),
                            Auto = 0,
                            Cell = "a137",
                            Producer = "Garden Fresh",
                            ProductName = "Zucchini",
                            QuantityInStock = 150,
                            SupplierID = new Guid("315e9973-c145-4bfd-985e-6a04aad99aeb"),
                            UnitPrice = 1777.00m,
                            WarehouseID = new Guid("c3fb3a21-ca5d-47e0-b5f6-1f3556cd01b3")
                        },
                        new
                        {
                            ID_Product = new Guid("e05974f2-7506-42b9-b18e-c4d6f849c5df"),
                            Auto = 0,
                            Cell = "a138",
                            Producer = "Tropical Goods",
                            ProductName = "Coconut Milk",
                            QuantityInStock = 110,
                            SupplierID = new Guid("89148db9-f165-4cb6-90f9-eb1a7b4e58e6"),
                            UnitPrice = 2777.50m,
                            WarehouseID = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42")
                        },
                        new
                        {
                            ID_Product = new Guid("cb69c898-b389-4a93-9130-f36b7d31b2ee"),
                            Auto = 0,
                            Cell = "a139",
                            Producer = "Asian Cuisine",
                            ProductName = "Rice Noodles",
                            QuantityInStock = 130,
                            SupplierID = new Guid("33b3d61a-77dc-4090-8f7c-858b8c8691cd"),
                            UnitPrice = 3777.50m,
                            WarehouseID = new Guid("79620bb0-fec4-4921-9b55-c3d1d9da57cc")
                        });
                });

            modelBuilder.Entity("DBase.Models.Supplier", b =>
                {
                    b.Property<Guid>("ID_Supplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ID_Supplier");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID_Supplier = new Guid("fb0fc0b4-f311-4bcb-ad20-b838b1ad1920"),
                            Auto = 0,
                            ContactName = "Alice",
                            Email = "alice@supplier.com",
                            Phone = "123-456-7890",
                            SupplierName = "Supplier A"
                        },
                        new
                        {
                            ID_Supplier = new Guid("315e9973-c145-4bfd-985e-6a04aad99aeb"),
                            Auto = 0,
                            ContactName = "Bob",
                            Email = "bob@supplier.com",
                            Phone = "098-765-4321",
                            SupplierName = "Supplier B"
                        },
                        new
                        {
                            ID_Supplier = new Guid("89148db9-f165-4cb6-90f9-eb1a7b4e58e6"),
                            Auto = 0,
                            ContactName = "Charlie",
                            Email = "charlie@supplier.com",
                            Phone = "321-654-0987",
                            SupplierName = "Supplier C"
                        },
                        new
                        {
                            ID_Supplier = new Guid("33b3d61a-77dc-4090-8f7c-858b8c8691cd"),
                            Auto = 0,
                            ContactName = "Diana",
                            Email = "diana@supplier.com",
                            Phone = "987-654-3210",
                            SupplierName = "Supplier D"
                        },
                        new
                        {
                            ID_Supplier = new Guid("39daa169-047e-4184-bd37-15f04b127175"),
                            Auto = 0,
                            ContactName = "John Doe",
                            Email = "john.doe@acmecorp.com",
                            Phone = "555-0101",
                            SupplierName = "Acme Corp"
                        },
                        new
                        {
                            ID_Supplier = new Guid("14fbefad-8f63-430f-82d0-c10d28f7862a"),
                            Auto = 0,
                            ContactName = "Jane Smith",
                            Email = "jane.smith@globalsupplies.com",
                            Phone = "555-0102",
                            SupplierName = "Global Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("d97d0cf9-9dd0-433a-9c98-08b75063a346"),
                            Auto = 0,
                            ContactName = "Alice Johnson",
                            Email = "alice.johnson@techinnovations.com",
                            Phone = "555-0103",
                            SupplierName = "Tech Innovations"
                        },
                        new
                        {
                            ID_Supplier = new Guid("7ddd3d5b-3bf3-41ea-a1de-e3f304ddfeea"),
                            Auto = 0,
                            ContactName = "Bob Brown",
                            Email = "bob.brown@qualitygoods.com",
                            Phone = "555-0104",
                            SupplierName = "Quality Goods"
                        },
                        new
                        {
                            ID_Supplier = new Guid("0857631e-4fce-4a52-b717-75c195dc1881"),
                            Auto = 0,
                            ContactName = "Charlie Davis",
                            Email = "charlie.davis@fastdelivery.com",
                            Phone = "555-0105",
                            SupplierName = "Fast Delivery"
                        },
                        new
                        {
                            ID_Supplier = new Guid("b7a01094-3afb-4e13-818a-59a931c2f48b"),
                            Auto = 0,
                            ContactName = "Diana Green",
                            Email = "diana.green@ecoproducts.com",
                            Phone = "555-0106",
                            SupplierName = "Eco Products"
                        },
                        new
                        {
                            ID_Supplier = new Guid("5a2d932c-6505-451f-877f-6be7273bb271"),
                            Auto = 0,
                            ContactName = "Ethan White",
                            Email = "ethan.white@homeessentials.com",
                            Phone = "555-0107",
                            SupplierName = "Home Essentials"
                        },
                        new
                        {
                            ID_Supplier = new Guid("71466897-d17c-49d1-9d9f-d8eb8670fd9c"),
                            Auto = 0,
                            ContactName = "Fiona Black",
                            Email = "fiona.black@officesuppliesco.com",
                            Phone = "555-0108",
                            SupplierName = "Office Supplies Co."
                        },
                        new
                        {
                            ID_Supplier = new Guid("f0566ed2-52ef-4ddc-9161-26bcb73b60bd"),
                            Auto = 0,
                            ContactName = "George Blue",
                            Email = "george.blue@gourmetfoods.com",
                            Phone = "555-0109",
                            SupplierName = "Gourmet Foods"
                        },
                        new
                        {
                            ID_Supplier = new Guid("7bb086a8-c6d7-48c2-9e13-d8b3316a0421"),
                            Auto = 0,
                            ContactName = "Hannah Red",
                            Email = "hannah.red@fashionhub.com",
                            Phone = "555-0110",
                            SupplierName = "Fashion Hub"
                        },
                        new
                        {
                            ID_Supplier = new Guid("22f8cce8-dad5-4d31-a827-35b2790c7348"),
                            Auto = 0,
                            ContactName = "Ian Gray",
                            Email = "ian.gray@healthwellness.com",
                            Phone = "555-0111",
                            SupplierName = "Health & Wellness"
                        },
                        new
                        {
                            ID_Supplier = new Guid("825256d5-a3d1-4985-af2d-aa01389b9dd7"),
                            Auto = 0,
                            ContactName = "Julia Orange",
                            Email = "julia.orange@sportsgear.com",
                            Phone = "555-0112",
                            SupplierName = "Sports Gear"
                        },
                        new
                        {
                            ID_Supplier = new Guid("00ec677e-f5d9-45bc-8f2e-df7d906b8921"),
                            Auto = 0,
                            ContactName = "Kevin Purple",
                            Email = "kevin.purple@petsupplies.com",
                            Phone = "555-0113",
                            SupplierName = "Pet Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("ba329989-ac8c-4044-9a7d-b7566f0355c1"),
                            Auto = 0,
                            ContactName = "Laura Pink",
                            Email = "laura.pink@automotiveparts.com",
                            Phone = "555-0114",
                            SupplierName = "Automotive Parts"
                        },
                        new
                        {
                            ID_Supplier = new Guid("33bd5409-2f0e-4d59-b21c-c4a9685b4ea0"),
                            Auto = 0,
                            ContactName = "Mike Yellow",
                            Email = "mike.yellow@constructionmaterials.com",
                            Phone = "555-0115",
                            SupplierName = "Construction Materials"
                        },
                        new
                        {
                            ID_Supplier = new Guid("c82e5c62-ea18-4c29-93dc-28b309561404"),
                            Auto = 0,
                            ContactName = "Nina Cyan",
                            Email = "nina.cyan@beveragedistributors.com",
                            Phone = "555-0116",
                            SupplierName = "Beverage Distributors"
                        },
                        new
                        {
                            ID_Supplier = new Guid("3d5eb318-3442-4200-9ed7-7cb267c816fd"),
                            Auto = 0,
                            ContactName = "Oscar Magenta",
                            Email = "oscar.magenta@cleaningsupplies.com",
                            Phone = "555-0117",
                            SupplierName = "Cleaning Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("15d152bd-1831-47ac-9a0a-f89d409ef70e"),
                            Auto = 0,
                            ContactName = "Paula Teal",
                            Email = "paula.teal@furnitureworld.com",
                            Phone = "555-0118",
                            SupplierName = "Furniture World"
                        },
                        new
                        {
                            ID_Supplier = new Guid("0da33d2b-1118-4635-bb96-5382a56747d3"),
                            Auto = 0,
                            ContactName = "Quinn Brown",
                            Email = "quinn.brown@gardensupplies.com",
                            Phone = "555-0119",
                            SupplierName = "Garden Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("ac9757bd-f556-4ec5-b80a-2cc8896e5bdf"),
                            Auto = 0,
                            ContactName = "Rachel Silver",
                            Email = "rachel.silver@digitalsolutions.com",
                            Phone = "555-0120",
                            SupplierName = "Digital Solutions"
                        });
                });

            modelBuilder.Entity("DBase.Models.Warehouse", b =>
                {
                    b.Property<Guid>("ID_Warehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ID_Warehouse");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            ID_Warehouse = new Guid("7c9914ff-256d-4beb-9ef8-c6eebaf1760e"),
                            Auto = 0,
                            Capacity = 50000,
                            Location = "Downtown",
                            ManagerName = "Alice Johnson",
                            WarehouseName = "Central Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("c3fb3a21-ca5d-47e0-b5f6-1f3556cd01b3"),
                            Auto = 0,
                            Capacity = 30000,
                            Location = "North District",
                            ManagerName = "Bob Smith",
                            WarehouseName = "Northside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("45a11d4e-5089-4ef9-83d2-5fea83a28e42"),
                            Auto = 0,
                            Capacity = 40000,
                            Location = "East District",
                            ManagerName = "Charlie Brown",
                            WarehouseName = "Eastside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("79620bb0-fec4-4921-9b55-c3d1d9da57cc"),
                            Auto = 0,
                            Capacity = 35000,
                            Location = "West District",
                            ManagerName = "Diana Prince",
                            WarehouseName = "Westside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("4f5e5098-3074-4dde-94cf-90ef7a2b56c3"),
                            Auto = 0,
                            Capacity = 4500,
                            Location = "South District",
                            ManagerName = "Ethan Hunt",
                            WarehouseName = "Southside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("67ab8e0f-fad1-4515-95a6-9114c3aeb382"),
                            Auto = 0,
                            Capacity = 6000,
                            Location = "Industrial Park",
                            ManagerName = "Fiona Green",
                            WarehouseName = "Logistics Hub"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("6b901674-76cd-4aca-8e3c-1d19c2732341"),
                            Auto = 0,
                            Capacity = 7000,
                            Location = "Airport Road",
                            ManagerName = "George White",
                            WarehouseName = "Distribution Center"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("839b4827-3e7f-4c35-9d2e-6e6501ac4f8e"),
                            Auto = 0,
                            Capacity = 2500,
                            Location = "Suburban Area",
                            ManagerName = "Hannah Blue",
                            WarehouseName = "Storage Facility"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("42bf36ef-7634-4ba8-8be5-b8a171ddab12"),
                            Auto = 0,
                            Capacity = 2000,
                            Location = "Market Street",
                            ManagerName = "Ian Gray",
                            WarehouseName = "Cold Storage"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("16274e2c-83ef-4ddd-b504-18a637e94a66"),
                            Auto = 0,
                            Capacity = 8000,
                            Location = "Port Area",
                            ManagerName = "Julia Red",
                            WarehouseName = "Bulk Storage"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("dc7eeb83-ee94-44fe-93eb-da812056e029"),
                            Auto = 0,
                            Capacity = 1000,
                            Location = "Location A",
                            ManagerName = "Manager A",
                            WarehouseName = "Warehouse 1"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("ea734f6f-b128-4202-9f81-337a0bf64783"),
                            Auto = 0,
                            Capacity = 2000,
                            Location = "Location B",
                            ManagerName = "Manager B",
                            WarehouseName = "Warehouse 2"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("3b4ed331-9392-4d7c-bf65-56a315c6efac"),
                            Auto = 0,
                            Capacity = 1500,
                            Location = "Location C",
                            ManagerName = "Manager C",
                            WarehouseName = "Warehouse 3"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("fca5864c-4e08-453e-979d-dc28807d2842"),
                            Auto = 0,
                            Capacity = 2500,
                            Location = "Location D",
                            ManagerName = "Manager D",
                            WarehouseName = "Warehouse 4"
                        });
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.HasOne("DBase.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBase.Models.OrderDetail", b =>
                {
                    b.HasOne("DBase.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBase.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.HasOne("DBase.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBase.Models.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DBase.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DBase.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DBase.Models.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
