// <auto-generated />
using System;
using DBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241122141905_FixOrder")]
    partial class FixOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBase.Models.Customer", b =>
                {
                    b.Property<Guid>("ID_Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID_Customer");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID_Customer = new Guid("de6dae74-ca42-4ef6-95c6-e4f2ccd69f5d"),
                            Address = "123 Main St, Anytown, USA",
                            Auto = 0,
                            CustomerName = "John Doe",
                            Email = "john.doe@example.com",
                            Phone = "111-222-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("24b4742d-16fe-4952-a520-0b4a331475a7"),
                            Address = "456 Elm St, Othertown, USA",
                            Auto = 0,
                            CustomerName = "Jane Smith",
                            Email = "jane.smith@example.com",
                            Phone = "444-555-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("441cc2ae-b2d9-49d0-b630-9f468cacbb62"),
                            Address = "789 Pine St, Sometown, USA",
                            Auto = 0,
                            CustomerName = "Alice Johnson",
                            Email = "alice.johnson@example.com",
                            Phone = "222-333-4444"
                        },
                        new
                        {
                            ID_Customer = new Guid("5c1a41ae-6d6e-46ab-bd82-49169506aa2c"),
                            Address = "321 Oak St, Anothertown, USA",
                            Auto = 0,
                            CustomerName = "Bob Brown",
                            Email = "bob.brown@example.com",
                            Phone = "555-666-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("d3b8b9f7-0ac0-4598-a29e-469e4cb68723"),
                            Address = "135 Maple St, Newtown, USA",
                            Auto = 0,
                            CustomerName = "Charlie Davis",
                            Email = "charlie.davis@example.com",
                            Phone = "888-999-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("f49847e4-eb96-4f97-aea4-ce7935686e36"),
                            Address = "246 Cedar St, Oldtown, USA",
                            Auto = 0,
                            CustomerName = "Diana Prince",
                            Email = "diana.prince@example.com",
                            Phone = "777-888-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("992fc6e3-aff7-4fae-be1d-1e8a092964fd"),
                            Address = "357 Birch St, Yourtown, USA",
                            Auto = 0,
                            CustomerName = "Ethan Hunt",
                            Email = "ethan.hunt@example.com",
                            Phone = "333-444-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("fa28d787-7b98-4edc-a94f-bd2b05d43eb7"),
                            Address = "468 Spruce St, Hometown, USA",
                            Auto = 0,
                            CustomerName = "Fiona Green",
                            Email = "fiona.green@example.com",
                            Phone = "666-777-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("16e1a3bf-cd29-4fcd-a8ca-9e08fcd3db6e"),
                            Address = "579 Fir St, Thistown, USA",
                            Auto = 0,
                            CustomerName = "George White",
                            Email = "george.white@example.com",
                            Phone = "999-000-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("181fc13a-5e8b-4933-b052-c69fd8b6b0dc"),
                            Address = "680 Willow St, Thatown, USA",
                            Auto = 0,
                            CustomerName = "Hannah Blue",
                            Email = "hannah.blue@example.com",
                            Phone = "222-111-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("c177b56c-5a97-4e82-960e-596ffc85bcfa"),
                            Address = "791 Ash St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Ian Gray",
                            Email = "ian.gray@example.com",
                            Phone = "444-222-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("0ec25c74-e709-455d-8c24-bf5c8a0ffd0e"),
                            Address = "802 Cherry St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Julia Red",
                            Email = "julia.red@example.com",
                            Phone = "555-333-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("957c7645-fb90-4fdd-b3e9-3d32efa33798"),
                            Address = "913 Peach St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Kevin Black",
                            Email = "kevin.black@example.com",
                            Phone = "666-444-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("2bbd6bc5-0639-428e-ae18-35f49e7dd7d2"),
                            Address = "024 Plum St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Laura Pink",
                            Email = "laura.pink@example.com",
                            Phone = "777-555-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("8dd656c7-8401-4228-999e-ea543409b517"),
                            Address = "135 Lemon St, Oldcity, USA",
                            Auto = 0,
                            CustomerName = "Mike Yellow",
                            Email = "mike.yellow@example.com",
                            Phone = "888-666-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("c1cba954-41e5-439b-ad83-06a60a52201c"),
                            Address = "246 Lime St, Yourcity, USA",
                            Auto = 0,
                            CustomerName = "Nina Cyan",
                            Email = "nina.cyan@example.com",
                            Phone = "999-777-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("15de8c1e-7568-437b-94cb-bee7037ee15b"),
                            Address = "357 Grape St, Thatcity, USA",
                            Auto = 0,
                            CustomerName = "Oscar Magenta",
                            Email = "oscar.magenta@example.com",
                            Phone = "000-888-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("7baab2a4-2f40-4601-8902-8cfae2cb1b89"),
                            Address = "468 Berry St, Thiscity, USA",
                            Auto = 0,
                            CustomerName = "Paula Teal",
                            Email = "paula.teal@example.com",
                            Phone = "111-999-2222"
                        },
                        new
                        {
                            ID_Customer = new Guid("2e61adc7-7fdf-4e90-8bcd-e0982f3b232e"),
                            Address = "579 Fig St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Quinn Brown",
                            Email = "quinn.brown@example.com",
                            Phone = "222-000-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("c19393fd-d964-4245-b6f0-4544c6ef892c"),
                            Address = "680 Date St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Rachel Silver",
                            Email = "rachel.silver@example.com",
                            Phone = "333-111-4444"
                        },
                        new
                        {
                            ID_Customer = new Guid("d1505e24-7ae2-4585-b700-5aab163eb192"),
                            Address = "791 Olive St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Steve Gold",
                            Email = "steve.gold@example.com",
                            Phone = "444-222-5555"
                        },
                        new
                        {
                            ID_Customer = new Guid("08c02564-5018-43ca-a685-8e7697a9ef0c"),
                            Address = "802 Walnut St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Tina Copper",
                            Email = "tina.copper@example.com",
                            Phone = "555-333-6666"
                        },
                        new
                        {
                            ID_Customer = new Guid("eea28bf0-eb7a-412c-b2b7-3789576198b7"),
                            Address = "913 Chestnut St, Oldcity, USA",
                            Auto = 0,
                            CustomerName = "Ursula Bronze",
                            Email = "ursula.bronze@example.com",
                            Phone = "666-444-7777"
                        },
                        new
                        {
                            ID_Customer = new Guid("d5b13830-820f-4ce9-8833-4055edf045bb"),
                            Address = "024 Maple St, Yourcity, USA",
                            Auto = 0,
                            CustomerName = "Victor Steel",
                            Email = "victor.steel@example.com",
                            Phone = "777-555-8888"
                        },
                        new
                        {
                            ID_Customer = new Guid("60654cb0-e74a-401e-8675-6f1fd832f1c2"),
                            Address = "135 Pineapple St, Thatcity, USA",
                            Auto = 0,
                            CustomerName = "Wendy Iron",
                            Email = "wendy.iron@example.com",
                            Phone = "888-666-9999"
                        },
                        new
                        {
                            ID_Customer = new Guid("334e649c-8c4c-4a70-94ca-4d458588ecd9"),
                            Address = "246 Coconut St, Thiscity, USA",
                            Auto = 0,
                            CustomerName = "Xander Zinc",
                            Email = "xander.zinc@example.com",
                            Phone = "999-777-0000"
                        },
                        new
                        {
                            ID_Customer = new Guid("d75dab49-a7bc-4b3b-b70a-8e75ddf0f11a"),
                            Address = "357 Papaya St, Anycity, USA",
                            Auto = 0,
                            CustomerName = "Yvonne Nickel",
                            Email = "yvonne.nickel@example.com",
                            Phone = "000-888-1111"
                        },
                        new
                        {
                            ID_Customer = new Guid("7d9dac09-0063-4c7b-861e-b6451040f7cc"),
                            Address = "680 Kiwi St, Somecity, USA",
                            Auto = 0,
                            CustomerName = "Zachary Lead",
                            Email = "zachary.lead@example.com",
                            Phone = "111-999-2222"
                        },
                        new
                        {
                            ID_Customer = new Guid("3eae8071-f7ec-4c8b-bff0-43d5d2980a85"),
                            Address = "791 Mango St, Othercity, USA",
                            Auto = 0,
                            CustomerName = "Alice Cooper",
                            Email = "alice.cooper@example.com",
                            Phone = "222-000-3333"
                        },
                        new
                        {
                            ID_Customer = new Guid("815ca9bd-442b-420c-b55e-7e9dcf9df7f3"),
                            Address = "802 Banana St, Newcity, USA",
                            Auto = 0,
                            CustomerName = "Bob Marley",
                            Email = "bob.marley@example.com",
                            Phone = "333-111-4444"
                        });
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.Property<Guid>("ID_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("ID_Order");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID_Order = new Guid("30eb9510-3f26-486c-aa13-b6262fb69b0e"),
                            Auto = 0,
                            CustomerID = new Guid("de6dae74-ca42-4ef6-95c6-e4f2ccd69f5d"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3466),
                            Status = "Completed",
                            TotalAmount = 35.00m
                        },
                        new
                        {
                            ID_Order = new Guid("be28d647-c9ea-4cd1-a365-ebd6b9b9b6d2"),
                            Auto = 0,
                            CustomerID = new Guid("24b4742d-16fe-4952-a520-0b4a331475a7"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3472),
                            Status = "Pending",
                            TotalAmount = 20.00m
                        },
                        new
                        {
                            ID_Order = new Guid("7318025b-fe5d-4a25-a9f3-afef7d83ebe2"),
                            Auto = 0,
                            CustomerID = new Guid("441cc2ae-b2d9-49d0-b630-9f468cacbb62"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3476),
                            Status = "Completed",
                            TotalAmount = 80.00m
                        },
                        new
                        {
                            ID_Order = new Guid("39cb2674-bfc0-4ab3-9da1-f822388ffa9c"),
                            Auto = 0,
                            CustomerID = new Guid("5c1a41ae-6d6e-46ab-bd82-49169506aa2c"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3480),
                            Status = "Shipped",
                            TotalAmount = 70.00m
                        },
                        new
                        {
                            ID_Order = new Guid("a84ef213-d5d1-4b88-9598-ab1d50945976"),
                            Auto = 0,
                            CustomerID = new Guid("d3b8b9f7-0ac0-4598-a29e-469e4cb68723"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3484),
                            Status = "Completed",
                            TotalAmount = 300.50m
                        },
                        new
                        {
                            ID_Order = new Guid("90327cc8-0605-40b0-91bf-f17b25a09e52"),
                            Auto = 0,
                            CustomerID = new Guid("f49847e4-eb96-4f97-aea4-ce7935686e36"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3488),
                            Status = "Pending",
                            TotalAmount = 300.50m
                        },
                        new
                        {
                            ID_Order = new Guid("b0cf6fad-e3e0-4153-99ce-bd960b348da4"),
                            Auto = 0,
                            CustomerID = new Guid("992fc6e3-aff7-4fae-be1d-1e8a092964fd"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3492),
                            Status = "Shipped",
                            TotalAmount = 6000.50m
                        },
                        new
                        {
                            ID_Order = new Guid("4c959a69-5354-4b3a-aae2-859a840c3b58"),
                            Auto = 0,
                            CustomerID = new Guid("fa28d787-7b98-4edc-a94f-bd2b05d43eb7"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3496),
                            Status = "Completed",
                            TotalAmount = 5001.30m
                        },
                        new
                        {
                            ID_Order = new Guid("81f2b9d2-eba5-43ec-8b18-5075eda47d88"),
                            Auto = 0,
                            CustomerID = new Guid("16e1a3bf-cd29-4fcd-a8ca-9e08fcd3db6e"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3500),
                            Status = "Pending",
                            TotalAmount = 11000.20m
                        },
                        new
                        {
                            ID_Order = new Guid("c761f43b-088d-4efe-b211-f31e6c42a173"),
                            Auto = 0,
                            CustomerID = new Guid("181fc13a-5e8b-4933-b052-c69fd8b6b0dc"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3504),
                            Status = "Completed",
                            TotalAmount = 3500.00m
                        },
                        new
                        {
                            ID_Order = new Guid("db67442d-f2de-44ba-b41b-a7712cc27320"),
                            Auto = 0,
                            CustomerID = new Guid("c177b56c-5a97-4e82-960e-596ffc85bcfa"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3507),
                            Status = "Pending",
                            TotalAmount = 800.00m
                        },
                        new
                        {
                            ID_Order = new Guid("c8643637-5b69-4af0-9a6d-3429d236d1df"),
                            Auto = 0,
                            CustomerID = new Guid("0ec25c74-e709-455d-8c24-bf5c8a0ffd0e"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3511),
                            Status = "Shipped",
                            TotalAmount = 1400.20m
                        },
                        new
                        {
                            ID_Order = new Guid("beec2dad-3809-4f16-84aa-bae57627bfa9"),
                            Auto = 0,
                            CustomerID = new Guid("957c7645-fb90-4fdd-b3e9-3d32efa33798"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3515),
                            Status = "Completed",
                            TotalAmount = 3201.00m
                        },
                        new
                        {
                            ID_Order = new Guid("874b6bd8-6437-45f1-ad27-af40ee1e9221"),
                            Auto = 0,
                            CustomerID = new Guid("2bbd6bc5-0639-428e-ae18-35f49e7dd7d2"),
                            OrderDate = new DateTime(2024, 11, 22, 14, 19, 4, 903, DateTimeKind.Utc).AddTicks(3519),
                            Status = "Pending",
                            TotalAmount = 6300.80m
                        });
                });

            modelBuilder.Entity("DBase.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("ID_OrderDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ID_OrderDetails");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            ID_OrderDetails = new Guid("65fc9065-546d-4aea-84b1-84e6a0f574a7"),
                            Auto = 0,
                            OrderId = new Guid("30eb9510-3f26-486c-aa13-b6262fb69b0e"),
                            ProductId = new Guid("ecabd6cd-c907-4f61-8659-308721950e03"),
                            Quantity = 2,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("e9cee9ad-a39a-45af-a3c9-e781753ef2e2"),
                            Auto = 0,
                            OrderId = new Guid("30eb9510-3f26-486c-aa13-b6262fb69b0e"),
                            ProductId = new Guid("c1b7e3dd-46ee-49ac-879e-5cb15ebe4480"),
                            Quantity = 1,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("ac7aa424-79e2-4929-8f96-e00e51b0b2f1"),
                            Auto = 0,
                            OrderId = new Guid("be28d647-c9ea-4cd1-a365-ebd6b9b9b6d2"),
                            ProductId = new Guid("9570aacc-51ed-45c3-b79f-ecfbc4352cb0"),
                            Quantity = 1,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("3dfcc6fa-d8c1-42f7-8917-4a559702ebf9"),
                            Auto = 0,
                            OrderId = new Guid("7318025b-fe5d-4a25-a9f3-afef7d83ebe2"),
                            ProductId = new Guid("386cb7d0-c604-47d5-9ad7-22dcc22510d2"),
                            Quantity = 2,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("75bd291d-23c7-49bb-ae2e-9ef8f7cce691"),
                            Auto = 0,
                            OrderId = new Guid("7318025b-fe5d-4a25-a9f3-afef7d83ebe2"),
                            ProductId = new Guid("5920611e-362f-428c-a273-6e1085c795ff"),
                            Quantity = 1,
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("9741fbd5-6886-49f5-b94f-c79cdc24fe03"),
                            Auto = 0,
                            OrderId = new Guid("39cb2674-bfc0-4ab3-9da1-f822388ffa9c"),
                            ProductId = new Guid("eb5e5f1f-730d-4876-9106-a0a341faa2ad"),
                            Quantity = 2,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("7bca3d48-0a0a-4ff2-bb3d-72ab848bca6e"),
                            Auto = 0,
                            OrderId = new Guid("a84ef213-d5d1-4b88-9598-ab1d50945976"),
                            ProductId = new Guid("52c220ad-b160-47c8-99ce-c6bcf0d3d0a1"),
                            Quantity = 1,
                            UnitPrice = 100.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("cfbc7a1d-c8b9-4ce6-91bf-1217150eb690"),
                            Auto = 0,
                            OrderId = new Guid("a84ef213-d5d1-4b88-9598-ab1d50945976"),
                            ProductId = new Guid("6ce0a939-fe14-4d26-bebc-c77ad67ca5c5"),
                            Quantity = 1,
                            UnitPrice = 200.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("f34be459-2b5b-4c30-8027-458fabc52917"),
                            Auto = 0,
                            OrderId = new Guid("90327cc8-0605-40b0-91bf-f17b25a09e52"),
                            ProductId = new Guid("0dc583e3-2692-4b21-87f6-eee8cab6e458"),
                            Quantity = 1,
                            UnitPrice = 300.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("5bc93166-3e7b-4b32-94a0-ad588efcbce3"),
                            Auto = 0,
                            OrderId = new Guid("b0cf6fad-e3e0-4153-99ce-bd960b348da4"),
                            ProductId = new Guid("6082b477-c64c-4b5e-8b64-7e84c499ea98"),
                            Quantity = 1,
                            UnitPrice = 4000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("5e7881ac-07e1-4728-80fb-8c95c66d5f8e"),
                            Auto = 0,
                            OrderId = new Guid("b0cf6fad-e3e0-4153-99ce-bd960b348da4"),
                            ProductId = new Guid("a31a169b-5c58-4d4d-afc9-1578ef17de0e"),
                            Quantity = 1,
                            UnitPrice = 2000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("90a066ca-fe11-4a2c-b415-f34052ac47c1"),
                            Auto = 0,
                            OrderId = new Guid("4c959a69-5354-4b3a-aae2-859a840c3b58"),
                            ProductId = new Guid("a4713f2f-2cdf-44e1-afc0-200ba0b9bfd1"),
                            Quantity = 1,
                            UnitPrice = 1000.80m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("50b5c1af-237f-4cd5-aa4c-1f9e2b3ae053"),
                            Auto = 0,
                            OrderId = new Guid("4c959a69-5354-4b3a-aae2-859a840c3b58"),
                            ProductId = new Guid("a70a1dd7-102d-4afb-adab-e0673aeddaaa"),
                            Quantity = 1,
                            UnitPrice = 4000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("20fee1be-9bf0-45f1-b013-7fda500ae5f5"),
                            Auto = 0,
                            OrderId = new Guid("81f2b9d2-eba5-43ec-8b18-5075eda47d88"),
                            ProductId = new Guid("1d126102-f297-4f5e-a387-432d117a178f"),
                            Quantity = 1,
                            UnitPrice = 6000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("ad1868b5-52ac-452a-be51-3187d2a85f42"),
                            Auto = 0,
                            OrderId = new Guid("81f2b9d2-eba5-43ec-8b18-5075eda47d88"),
                            ProductId = new Guid("646fbdce-e801-4f2f-91c7-c196362f6b7b"),
                            Quantity = 1,
                            UnitPrice = 3000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("4eeaa75c-2b41-405c-a5d4-13f954a64c46"),
                            Auto = 0,
                            OrderId = new Guid("81f2b9d2-eba5-43ec-8b18-5075eda47d88"),
                            ProductId = new Guid("73d7c52f-176b-49ed-89ff-ad6f07521687"),
                            Quantity = 1,
                            UnitPrice = 2000.20m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("d49a2309-f4ae-48c0-894d-4438b7577d8f"),
                            Auto = 0,
                            OrderId = new Guid("c761f43b-088d-4efe-b211-f31e6c42a173"),
                            ProductId = new Guid("f69e4b89-6144-4c54-880d-9ea214d764b1"),
                            Quantity = 1,
                            UnitPrice = 3000.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("d45aedb8-c0e6-48b8-b835-a1839e272047"),
                            Auto = 0,
                            OrderId = new Guid("c761f43b-088d-4efe-b211-f31e6c42a173"),
                            ProductId = new Guid("4270c1f7-6610-4e54-8e79-5016ac00e18a"),
                            Quantity = 1,
                            UnitPrice = 500.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("f3c0cb21-f38a-4daa-bd3f-bd0b35925aad"),
                            Auto = 0,
                            OrderId = new Guid("db67442d-f2de-44ba-b41b-a7712cc27320"),
                            ProductId = new Guid("d4ef38f1-cbf4-47ee-a7ae-72ca3d030159"),
                            Quantity = 1,
                            UnitPrice = 800.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("92dc4106-f5a8-4d0e-a6a5-41f735f892ea"),
                            Auto = 0,
                            OrderId = new Guid("c8643637-5b69-4af0-9a6d-3429d236d1df"),
                            ProductId = new Guid("45f64507-75a8-41d9-b178-f6c0be3ae039"),
                            Quantity = 1,
                            UnitPrice = 1000.20m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("39eff660-b936-4f47-91fb-2871744cbbcc"),
                            Auto = 0,
                            OrderId = new Guid("c8643637-5b69-4af0-9a6d-3429d236d1df"),
                            ProductId = new Guid("02c58195-8d04-4106-987b-6205e2bd582d"),
                            Quantity = 1,
                            UnitPrice = 400.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("d1b41f40-748d-4e8d-bace-312a87cf816a"),
                            Auto = 0,
                            OrderId = new Guid("beec2dad-3809-4f16-84aa-bae57627bfa9"),
                            ProductId = new Guid("22712885-e0cd-40b6-ac06-db6cf07f7e59"),
                            Quantity = 1,
                            UnitPrice = 3000.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("cd989b02-e514-408c-8d89-c380121ff2dd"),
                            Auto = 0,
                            OrderId = new Guid("beec2dad-3809-4f16-84aa-bae57627bfa9"),
                            ProductId = new Guid("9b4ddf17-05e4-4d09-9ffa-1a1783deff38"),
                            Quantity = 1,
                            UnitPrice = 200.50m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("f2ff20bf-606a-4e09-b078-52c85c1faee2"),
                            Auto = 0,
                            OrderId = new Guid("874b6bd8-6437-45f1-ad27-af40ee1e9221"),
                            ProductId = new Guid("c449035c-eb8c-4c9c-9777-6d709d5514c9"),
                            Quantity = 1,
                            UnitPrice = 100.80m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("640904f7-f688-4643-a71c-541339eec669"),
                            Auto = 0,
                            OrderId = new Guid("874b6bd8-6437-45f1-ad27-af40ee1e9221"),
                            ProductId = new Guid("ddaafc36-f7c7-438f-bedc-e754b148da68"),
                            Quantity = 1,
                            UnitPrice = 200.00m
                        },
                        new
                        {
                            ID_OrderDetails = new Guid("bf3acefc-8c06-41a4-9346-11b2cf898b79"),
                            Auto = 0,
                            OrderId = new Guid("874b6bd8-6437-45f1-ad27-af40ee1e9221"),
                            ProductId = new Guid("b7a50599-43ee-4205-975f-cd8d282dc3ec"),
                            Quantity = 1,
                            UnitPrice = 6000.00m
                        });
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.Property<Guid>("ID_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("Cell")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Producer")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WarehouseID")
                        .HasColumnType("uuid");

                    b.HasKey("ID_Product");

                    b.HasIndex("SupplierID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID_Product = new Guid("ecabd6cd-c907-4f61-8659-308721950e03"),
                            Auto = 0,
                            Cell = "a100",
                            Producer = "Producer 1",
                            ProductName = "Product 1",
                            QuantityInStock = 100,
                            SupplierID = new Guid("5636731c-722c-4c85-9d6f-452f4904a50d"),
                            UnitPrice = 10.00m,
                            WarehouseID = new Guid("18424185-38c4-494d-99a1-9243c270528c")
                        },
                        new
                        {
                            ID_Product = new Guid("c1b7e3dd-46ee-49ac-879e-5cb15ebe4480"),
                            Auto = 0,
                            Cell = "a101",
                            Producer = "Producer 2",
                            ProductName = "Product 2",
                            QuantityInStock = 200,
                            SupplierID = new Guid("5636731c-722c-4c85-9d6f-452f4904a50d"),
                            UnitPrice = 15.00m,
                            WarehouseID = new Guid("18424185-38c4-494d-99a1-9243c270528c")
                        },
                        new
                        {
                            ID_Product = new Guid("9570aacc-51ed-45c3-b79f-ecfbc4352cb0"),
                            Auto = 0,
                            Cell = "a102",
                            Producer = "Producer 2",
                            ProductName = "Product 3",
                            QuantityInStock = 150,
                            SupplierID = new Guid("2b7e4611-7977-409c-9872-73aad4cbddab"),
                            UnitPrice = 20.00m,
                            WarehouseID = new Guid("0bb9f8e0-0500-40e8-88f8-62b1d6b4b451")
                        },
                        new
                        {
                            ID_Product = new Guid("386cb7d0-c604-47d5-9ad7-22dcc22510d2"),
                            Auto = 0,
                            Cell = "a103",
                            Producer = "Producer 2",
                            ProductName = "Product 4",
                            QuantityInStock = 80,
                            SupplierID = new Guid("49283e03-ec1f-4eb1-977c-a96fe799c63d"),
                            UnitPrice = 25.00m,
                            WarehouseID = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f")
                        },
                        new
                        {
                            ID_Product = new Guid("5920611e-362f-428c-a273-6e1085c795ff"),
                            Auto = 0,
                            Cell = "a104",
                            Producer = "Producer 3",
                            ProductName = "Product 5",
                            QuantityInStock = 60,
                            SupplierID = new Guid("49283e03-ec1f-4eb1-977c-a96fe799c63d"),
                            UnitPrice = 30.00m,
                            WarehouseID = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f")
                        },
                        new
                        {
                            ID_Product = new Guid("eb5e5f1f-730d-4876-9106-a0a341faa2ad"),
                            Auto = 0,
                            Cell = "a105",
                            Producer = "Producer 3",
                            ProductName = "Product 6",
                            QuantityInStock = 40,
                            SupplierID = new Guid("b4e43cb3-97e2-4e95-9945-7fe0efb90dfc"),
                            UnitPrice = 35.00m,
                            WarehouseID = new Guid("f6df8f8f-9eb0-4332-a1a6-5707ba8003d9")
                        },
                        new
                        {
                            ID_Product = new Guid("52c220ad-b160-47c8-99ce-c6bcf0d3d0a1"),
                            Auto = 0,
                            Cell = "a10",
                            Producer = "Fresh Farms",
                            ProductName = "Organic Apples",
                            QuantityInStock = 150,
                            SupplierID = new Guid("150ff357-4e1b-4257-90f4-7da242f3ffaa"),
                            UnitPrice = 100.50m,
                            WarehouseID = new Guid("5660eaea-4240-4362-9b13-403a765bbc54")
                        },
                        new
                        {
                            ID_Product = new Guid("6ce0a939-fe14-4d26-bebc-c77ad67ca5c5"),
                            Auto = 0,
                            Cell = "a11",
                            Producer = "Bakery Co.",
                            ProductName = "Whole Wheat Bread",
                            QuantityInStock = 200,
                            SupplierID = new Guid("150ff357-4e1b-4257-90f4-7da242f3ffaa"),
                            UnitPrice = 200.00m,
                            WarehouseID = new Guid("5660eaea-4240-4362-9b13-403a765bbc54")
                        },
                        new
                        {
                            ID_Product = new Guid("0dc583e3-2692-4b21-87f6-eee8cab6e458"),
                            Auto = 0,
                            Cell = "a12",
                            Producer = "Nutty Delights",
                            ProductName = "Almond Milk",
                            QuantityInStock = 100,
                            SupplierID = new Guid("622eb028-4176-4e50-b7b1-fd061b1c12c0"),
                            UnitPrice = 300.50m,
                            WarehouseID = new Guid("e60a4bcd-9372-4524-a3b8-7fe95158b845")
                        },
                        new
                        {
                            ID_Product = new Guid("6082b477-c64c-4b5e-8b64-7e84c499ea98"),
                            Auto = 0,
                            Cell = "a13",
                            Producer = "Dairy Best",
                            ProductName = "Greek Yogurt",
                            QuantityInStock = 80,
                            SupplierID = new Guid("622eb028-4176-4e50-b7b1-fd061b1c12c0"),
                            UnitPrice = 4000.00m,
                            WarehouseID = new Guid("c6aef0fe-4974-41ba-bfd7-7502ebb9967a")
                        },
                        new
                        {
                            ID_Product = new Guid("a31a169b-5c58-4d4d-afc9-1578ef17de0e"),
                            Auto = 0,
                            Cell = "a14",
                            Producer = "Farm Fresh",
                            ProductName = "Free-Range Eggs",
                            QuantityInStock = 60,
                            SupplierID = new Guid("622eb028-4176-4e50-b7b1-fd061b1c12c0"),
                            UnitPrice = 2000.50m,
                            WarehouseID = new Guid("c6aef0fe-4974-41ba-bfd7-7502ebb9967a")
                        },
                        new
                        {
                            ID_Product = new Guid("a4713f2f-2cdf-44e1-afc0-200ba0b9bfd1"),
                            Auto = 0,
                            Cell = "a15",
                            Producer = "Grain Masters",
                            ProductName = "Brown Rice",
                            QuantityInStock = 120,
                            SupplierID = new Guid("425882c1-de8b-4c50-a464-e667c9e8bf96"),
                            UnitPrice = 1000.80m,
                            WarehouseID = new Guid("548245ff-5cb1-48bc-a855-43c744f2fc35")
                        },
                        new
                        {
                            ID_Product = new Guid("a70a1dd7-102d-4afb-adab-e0673aeddaaa"),
                            Auto = 0,
                            Cell = "a106",
                            Producer = "Healthy Grains",
                            ProductName = "Quinoa",
                            QuantityInStock = 90,
                            SupplierID = new Guid("425882c1-de8b-4c50-a464-e667c9e8bf96"),
                            UnitPrice = 4000.50m,
                            WarehouseID = new Guid("548245ff-5cb1-48bc-a855-43c744f2fc35")
                        },
                        new
                        {
                            ID_Product = new Guid("1d126102-f297-4f5e-a387-432d117a178f"),
                            Auto = 0,
                            Cell = "a107",
                            Producer = "Tropical Goods",
                            ProductName = "Coconut Oil",
                            QuantityInStock = 70,
                            SupplierID = new Guid("425882c1-de8b-4c50-a464-e667c9e8bf96"),
                            UnitPrice = 6000.00m,
                            WarehouseID = new Guid("e60a4bcd-9372-4524-a3b8-7fe95158b845")
                        },
                        new
                        {
                            ID_Product = new Guid("646fbdce-e801-4f2f-91c7-c196362f6b7b"),
                            Auto = 0,
                            Cell = "a108",
                            Producer = "Choco Bliss",
                            ProductName = "Dark Chocolate",
                            QuantityInStock = 50,
                            SupplierID = new Guid("9939120d-d873-44d0-9f94-149f43b78739"),
                            UnitPrice = 3000.00m,
                            WarehouseID = new Guid("29733313-63c1-4b11-bcbe-43ab106b1259")
                        },
                        new
                        {
                            ID_Product = new Guid("73d7c52f-176b-49ed-89ff-ad6f07521687"),
                            Auto = 0,
                            Cell = "a109",
                            Producer = "Green Leaf",
                            ProductName = "Spinach",
                            QuantityInStock = 110,
                            SupplierID = new Guid("00f472e3-e729-4c4b-afb4-47b7b4bf942d"),
                            UnitPrice = 2000.20m,
                            WarehouseID = new Guid("58e3105d-db58-4960-ab72-de93a731a60a")
                        },
                        new
                        {
                            ID_Product = new Guid("f69e4b89-6144-4c54-880d-9ea214d764b1"),
                            Auto = 0,
                            Cell = "a110",
                            Producer = "Healthy Mornings",
                            ProductName = "Oatmeal",
                            QuantityInStock = 200,
                            SupplierID = new Guid("583539ac-99ff-4810-b062-4ab12b4eee2e"),
                            UnitPrice = 3000.00m,
                            WarehouseID = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f")
                        },
                        new
                        {
                            ID_Product = new Guid("4270c1f7-6610-4e54-8e79-5016ac00e18a"),
                            Auto = 0,
                            Cell = "a111",
                            Producer = "Superfoods Co.",
                            ProductName = "Chia Seeds",
                            QuantityInStock = 150,
                            SupplierID = new Guid("306a79d3-dd09-463b-aed3-999231eeb121"),
                            UnitPrice = 500.00m,
                            WarehouseID = new Guid("fedf9557-059f-4eea-b5b0-29203109e14b")
                        },
                        new
                        {
                            ID_Product = new Guid("d4ef38f1-cbf4-47ee-a7ae-72ca3d030159"),
                            Auto = 0,
                            Cell = "a112",
                            Producer = "Nature's Best",
                            ProductName = "Avocado Oil",
                            QuantityInStock = 80,
                            SupplierID = new Guid("5f5805c9-30be-4768-bf5c-9e1e7df831aa"),
                            UnitPrice = 800.00m,
                            WarehouseID = new Guid("c6aef0fe-4974-41ba-bfd7-7502ebb9967a")
                        },
                        new
                        {
                            ID_Product = new Guid("45f64507-75a8-41d9-b178-f6c0be3ae039"),
                            Auto = 0,
                            Cell = "a113",
                            Producer = "Legume Lovers",
                            ProductName = "Canned Chickpeas",
                            QuantityInStock = 300,
                            SupplierID = new Guid("681cf02d-f394-45dc-8a0f-5dfb24c16d01"),
                            UnitPrice = 1000.20m,
                            WarehouseID = new Guid("548245ff-5cb1-48bc-a855-43c744f2fc35")
                        },
                        new
                        {
                            ID_Product = new Guid("02c58195-8d04-4106-987b-6205e2bd582d"),
                            Auto = 0,
                            Cell = "a114",
                            Producer = "Berry Good",
                            ProductName = "Frozen Berries",
                            QuantityInStock = 120,
                            SupplierID = new Guid("822c14bf-bb0f-468f-bd5f-77e16183700f"),
                            UnitPrice = 400.00m,
                            WarehouseID = new Guid("e60a4bcd-9372-4524-a3b8-7fe95158b845")
                        },
                        new
                        {
                            ID_Product = new Guid("22712885-e0cd-40b6-ac06-db6cf07f7e59"),
                            Auto = 0,
                            Cell = "a115",
                            Producer = "Nutty Spread",
                            ProductName = "Peanut Butter",
                            QuantityInStock = 90,
                            SupplierID = new Guid("8a7047d7-4c81-4aed-8bdb-d114e3eee048"),
                            UnitPrice = 3000.50m,
                            WarehouseID = new Guid("0d21dfff-cea4-4304-9306-0e4beb5950b1")
                        },
                        new
                        {
                            ID_Product = new Guid("9b4ddf17-05e4-4d09-9ffa-1a1783deff38"),
                            Auto = 0,
                            Cell = "a116",
                            Producer = "Tropical Refreshments",
                            ProductName = "Coconut Water",
                            QuantityInStock = 200,
                            SupplierID = new Guid("468b2e06-394b-44e3-914f-be7924c10f8d"),
                            UnitPrice = 200.50m,
                            WarehouseID = new Guid("74795400-2abb-40bf-9a3c-88d7bcccd648")
                        },
                        new
                        {
                            ID_Product = new Guid("c449035c-eb8c-4c9c-9777-6d709d5514c9"),
                            Auto = 0,
                            Cell = "a117",
                            Producer = "Snack Time",
                            ProductName = "Granola Bars",
                            QuantityInStock = 150,
                            SupplierID = new Guid("cf34d94c-7388-4324-ab89-1a6144eba52c"),
                            UnitPrice = 100.80m,
                            WarehouseID = new Guid("29733313-63c1-4b11-bcbe-43ab106b1259")
                        },
                        new
                        {
                            ID_Product = new Guid("ddaafc36-f7c7-438f-bedc-e754b148da68"),
                            Auto = 0,
                            Cell = "a118",
                            Producer = "Dips & Spreads",
                            ProductName = "Hummus",
                            QuantityInStock = 100,
                            SupplierID = new Guid("819c4baa-aacd-4b59-94f0-698f5ba47072"),
                            UnitPrice = 200.00m,
                            WarehouseID = new Guid("58e3105d-db58-4960-ab72-de93a731a60a")
                        },
                        new
                        {
                            ID_Product = new Guid("b7a50599-43ee-4205-975f-cd8d282dc3ec"),
                            Auto = 0,
                            Cell = "a119",
                            Producer = "Sweet Harvest",
                            ProductName = "Maple Syrup",
                            QuantityInStock = 70,
                            SupplierID = new Guid("26672d2c-5bfa-40cd-9a24-b15d3be0c2be"),
                            UnitPrice = 6000.00m,
                            WarehouseID = new Guid("b879b027-9089-4574-a773-7bcd5b150b3f")
                        },
                        new
                        {
                            ID_Product = new Guid("3000aba2-70eb-4b0f-8801-fcbb05379828"),
                            Auto = 0,
                            Cell = "a126",
                            Producer = "Root Veggies",
                            ProductName = "Sweet Potatoes",
                            QuantityInStock = 120,
                            SupplierID = new Guid("49283e03-ec1f-4eb1-977c-a96fe799c63d"),
                            UnitPrice = 100.80m,
                            WarehouseID = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f")
                        },
                        new
                        {
                            ID_Product = new Guid("925c7bbb-bb82-4754-befd-2f4c176b34d7"),
                            Auto = 0,
                            Cell = "a127",
                            Producer = "Garden Fresh",
                            ProductName = "Canned Tomatoes",
                            QuantityInStock = 300,
                            SupplierID = new Guid("b4e43cb3-97e2-4e95-9945-7fe0efb90dfc"),
                            UnitPrice = 1000.00m,
                            WarehouseID = new Guid("f6df8f8f-9eb0-4332-a1a6-5707ba8003d9")
                        },
                        new
                        {
                            ID_Product = new Guid("ddd739d0-d947-4dd6-bca6-74434ddd059f"),
                            Auto = 0,
                            Cell = "a128",
                            Producer = "Healthy Snacks",
                            ProductName = "Nut Mix",
                            QuantityInStock = 90,
                            SupplierID = new Guid("2b7e4611-7977-409c-9872-73aad4cbddab"),
                            UnitPrice = 600.00m,
                            WarehouseID = new Guid("0bb9f8e0-0500-40e8-88f8-62b1d6b4b451")
                        },
                        new
                        {
                            ID_Product = new Guid("7b81bb69-5c13-41af-9cda-5223d1e28944"),
                            Auto = 0,
                            Cell = "a129",
                            Producer = "Gourmet Essentials",
                            ProductName = "Balsamic Vinegar",
                            QuantityInStock = 70,
                            SupplierID = new Guid("5636731c-722c-4c85-9d6f-452f4904a50d"),
                            UnitPrice = 4000.50m,
                            WarehouseID = new Guid("18424185-38c4-494d-99a1-9243c270528c")
                        },
                        new
                        {
                            ID_Product = new Guid("96b1a41c-8b34-495b-b76f-58451a206e4c"),
                            Auto = 0,
                            Cell = "a130",
                            Producer = "Plant Protein Co.",
                            ProductName = "Tofu",
                            QuantityInStock = 100,
                            SupplierID = new Guid("26672d2c-5bfa-40cd-9a24-b15d3be0c2be"),
                            UnitPrice = 200.50m,
                            WarehouseID = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f")
                        },
                        new
                        {
                            ID_Product = new Guid("92fe2ca3-6717-4194-abbb-f16ef82ce71f"),
                            Auto = 0,
                            Cell = "a131",
                            Producer = "Nutty Delights",
                            ProductName = "Almonds",
                            QuantityInStock = 80,
                            SupplierID = new Guid("819c4baa-aacd-4b59-94f0-698f5ba47072"),
                            UnitPrice = 8000.00m,
                            WarehouseID = new Guid("f6df8f8f-9eb0-4332-a1a6-5707ba8003d9")
                        },
                        new
                        {
                            ID_Product = new Guid("67e05ad3-708d-4a0f-8ceb-0de7f1521dc8"),
                            Auto = 0,
                            Cell = "a132",
                            Producer = "Spice World",
                            ProductName = "Cinnamon",
                            QuantityInStock = 150,
                            SupplierID = new Guid("cf34d94c-7388-4324-ab89-1a6144eba52c"),
                            UnitPrice = 300.00m,
                            WarehouseID = new Guid("18424185-38c4-494d-99a1-9243c270528c")
                        },
                        new
                        {
                            ID_Product = new Guid("aee79716-865e-4c46-a528-839efb7c2b7f"),
                            Auto = 0,
                            Cell = "a133",
                            Producer = "Legume Lovers",
                            ProductName = "Black Beans",
                            QuantityInStock = 200,
                            SupplierID = new Guid("f558f1db-72a1-4347-8472-7715f43772d6"),
                            UnitPrice = 100.50m,
                            WarehouseID = new Guid("0bb9f8e0-0500-40e8-88f8-62b1d6b4b451")
                        },
                        new
                        {
                            ID_Product = new Guid("fb24b90f-a154-4790-9879-2cd0a2b7b01e"),
                            Auto = 0,
                            Cell = "a134",
                            Producer = "Fresh Greens",
                            ProductName = "Cabbage",
                            QuantityInStock = 120,
                            SupplierID = new Guid("d7b77dc7-16d0-430b-9427-8bc2714c30e0"),
                            UnitPrice = 166.80m,
                            WarehouseID = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f")
                        },
                        new
                        {
                            ID_Product = new Guid("878f48a7-db76-449f-a750-8bf7c41da1d3"),
                            Auto = 0,
                            Cell = "a135",
                            Producer = "Healthy Harvest",
                            ProductName = "Lentils",
                            QuantityInStock = 180,
                            SupplierID = new Guid("150ff357-4e1b-4257-90f4-7da242f3ffaa"),
                            UnitPrice = 177.20m,
                            WarehouseID = new Guid("f6df8f8f-9eb0-4332-a1a6-5707ba8003d9")
                        },
                        new
                        {
                            ID_Product = new Guid("2a81ea83-c027-48e6-ad93-b1314f804ff1"),
                            Auto = 0,
                            Cell = "a136",
                            Producer = "Snack Time",
                            ProductName = "Pumpkin Seeds",
                            QuantityInStock = 90,
                            SupplierID = new Guid("622eb028-4176-4e50-b7b1-fd061b1c12c0"),
                            UnitPrice = 4777.00m,
                            WarehouseID = new Guid("18424185-38c4-494d-99a1-9243c270528c")
                        },
                        new
                        {
                            ID_Product = new Guid("0c37c3dc-0322-419e-b7b7-eb7216f01af2"),
                            Auto = 0,
                            Cell = "a137",
                            Producer = "Garden Fresh",
                            ProductName = "Zucchini",
                            QuantityInStock = 150,
                            SupplierID = new Guid("2b7e4611-7977-409c-9872-73aad4cbddab"),
                            UnitPrice = 1777.00m,
                            WarehouseID = new Guid("0bb9f8e0-0500-40e8-88f8-62b1d6b4b451")
                        },
                        new
                        {
                            ID_Product = new Guid("d725d188-f960-41c9-a3cc-000b81f48e5e"),
                            Auto = 0,
                            Cell = "a138",
                            Producer = "Tropical Goods",
                            ProductName = "Coconut Milk",
                            QuantityInStock = 110,
                            SupplierID = new Guid("49283e03-ec1f-4eb1-977c-a96fe799c63d"),
                            UnitPrice = 2777.50m,
                            WarehouseID = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f")
                        },
                        new
                        {
                            ID_Product = new Guid("3cfa5bb1-5871-47eb-924d-da44f31eb32c"),
                            Auto = 0,
                            Cell = "a139",
                            Producer = "Asian Cuisine",
                            ProductName = "Rice Noodles",
                            QuantityInStock = 130,
                            SupplierID = new Guid("b4e43cb3-97e2-4e95-9945-7fe0efb90dfc"),
                            UnitPrice = 3777.50m,
                            WarehouseID = new Guid("f6df8f8f-9eb0-4332-a1a6-5707ba8003d9")
                        });
                });

            modelBuilder.Entity("DBase.Models.Supplier", b =>
                {
                    b.Property<Guid>("ID_Supplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ID_Supplier");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID_Supplier = new Guid("5636731c-722c-4c85-9d6f-452f4904a50d"),
                            Auto = 0,
                            ContactName = "Alice",
                            Email = "alice@supplier.com",
                            Phone = "123-456-7890",
                            SupplierName = "Supplier A"
                        },
                        new
                        {
                            ID_Supplier = new Guid("2b7e4611-7977-409c-9872-73aad4cbddab"),
                            Auto = 0,
                            ContactName = "Bob",
                            Email = "bob@supplier.com",
                            Phone = "098-765-4321",
                            SupplierName = "Supplier B"
                        },
                        new
                        {
                            ID_Supplier = new Guid("49283e03-ec1f-4eb1-977c-a96fe799c63d"),
                            Auto = 0,
                            ContactName = "Charlie",
                            Email = "charlie@supplier.com",
                            Phone = "321-654-0987",
                            SupplierName = "Supplier C"
                        },
                        new
                        {
                            ID_Supplier = new Guid("b4e43cb3-97e2-4e95-9945-7fe0efb90dfc"),
                            Auto = 0,
                            ContactName = "Diana",
                            Email = "diana@supplier.com",
                            Phone = "987-654-3210",
                            SupplierName = "Supplier D"
                        },
                        new
                        {
                            ID_Supplier = new Guid("583539ac-99ff-4810-b062-4ab12b4eee2e"),
                            Auto = 0,
                            ContactName = "John Doe",
                            Email = "john.doe@acmecorp.com",
                            Phone = "555-0101",
                            SupplierName = "Acme Corp"
                        },
                        new
                        {
                            ID_Supplier = new Guid("306a79d3-dd09-463b-aed3-999231eeb121"),
                            Auto = 0,
                            ContactName = "Jane Smith",
                            Email = "jane.smith@globalsupplies.com",
                            Phone = "555-0102",
                            SupplierName = "Global Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("5f5805c9-30be-4768-bf5c-9e1e7df831aa"),
                            Auto = 0,
                            ContactName = "Alice Johnson",
                            Email = "alice.johnson@techinnovations.com",
                            Phone = "555-0103",
                            SupplierName = "Tech Innovations"
                        },
                        new
                        {
                            ID_Supplier = new Guid("8a7047d7-4c81-4aed-8bdb-d114e3eee048"),
                            Auto = 0,
                            ContactName = "Bob Brown",
                            Email = "bob.brown@qualitygoods.com",
                            Phone = "555-0104",
                            SupplierName = "Quality Goods"
                        },
                        new
                        {
                            ID_Supplier = new Guid("822c14bf-bb0f-468f-bd5f-77e16183700f"),
                            Auto = 0,
                            ContactName = "Charlie Davis",
                            Email = "charlie.davis@fastdelivery.com",
                            Phone = "555-0105",
                            SupplierName = "Fast Delivery"
                        },
                        new
                        {
                            ID_Supplier = new Guid("681cf02d-f394-45dc-8a0f-5dfb24c16d01"),
                            Auto = 0,
                            ContactName = "Diana Green",
                            Email = "diana.green@ecoproducts.com",
                            Phone = "555-0106",
                            SupplierName = "Eco Products"
                        },
                        new
                        {
                            ID_Supplier = new Guid("468b2e06-394b-44e3-914f-be7924c10f8d"),
                            Auto = 0,
                            ContactName = "Ethan White",
                            Email = "ethan.white@homeessentials.com",
                            Phone = "555-0107",
                            SupplierName = "Home Essentials"
                        },
                        new
                        {
                            ID_Supplier = new Guid("26672d2c-5bfa-40cd-9a24-b15d3be0c2be"),
                            Auto = 0,
                            ContactName = "Fiona Black",
                            Email = "fiona.black@officesuppliesco.com",
                            Phone = "555-0108",
                            SupplierName = "Office Supplies Co."
                        },
                        new
                        {
                            ID_Supplier = new Guid("819c4baa-aacd-4b59-94f0-698f5ba47072"),
                            Auto = 0,
                            ContactName = "George Blue",
                            Email = "george.blue@gourmetfoods.com",
                            Phone = "555-0109",
                            SupplierName = "Gourmet Foods"
                        },
                        new
                        {
                            ID_Supplier = new Guid("cf34d94c-7388-4324-ab89-1a6144eba52c"),
                            Auto = 0,
                            ContactName = "Hannah Red",
                            Email = "hannah.red@fashionhub.com",
                            Phone = "555-0110",
                            SupplierName = "Fashion Hub"
                        },
                        new
                        {
                            ID_Supplier = new Guid("f558f1db-72a1-4347-8472-7715f43772d6"),
                            Auto = 0,
                            ContactName = "Ian Gray",
                            Email = "ian.gray@healthwellness.com",
                            Phone = "555-0111",
                            SupplierName = "Health & Wellness"
                        },
                        new
                        {
                            ID_Supplier = new Guid("d7b77dc7-16d0-430b-9427-8bc2714c30e0"),
                            Auto = 0,
                            ContactName = "Julia Orange",
                            Email = "julia.orange@sportsgear.com",
                            Phone = "555-0112",
                            SupplierName = "Sports Gear"
                        },
                        new
                        {
                            ID_Supplier = new Guid("150ff357-4e1b-4257-90f4-7da242f3ffaa"),
                            Auto = 0,
                            ContactName = "Kevin Purple",
                            Email = "kevin.purple@petsupplies.com",
                            Phone = "555-0113",
                            SupplierName = "Pet Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("622eb028-4176-4e50-b7b1-fd061b1c12c0"),
                            Auto = 0,
                            ContactName = "Laura Pink",
                            Email = "laura.pink@automotiveparts.com",
                            Phone = "555-0114",
                            SupplierName = "Automotive Parts"
                        },
                        new
                        {
                            ID_Supplier = new Guid("425882c1-de8b-4c50-a464-e667c9e8bf96"),
                            Auto = 0,
                            ContactName = "Mike Yellow",
                            Email = "mike.yellow@constructionmaterials.com",
                            Phone = "555-0115",
                            SupplierName = "Construction Materials"
                        },
                        new
                        {
                            ID_Supplier = new Guid("9939120d-d873-44d0-9f94-149f43b78739"),
                            Auto = 0,
                            ContactName = "Nina Cyan",
                            Email = "nina.cyan@beveragedistributors.com",
                            Phone = "555-0116",
                            SupplierName = "Beverage Distributors"
                        },
                        new
                        {
                            ID_Supplier = new Guid("00f472e3-e729-4c4b-afb4-47b7b4bf942d"),
                            Auto = 0,
                            ContactName = "Oscar Magenta",
                            Email = "oscar.magenta@cleaningsupplies.com",
                            Phone = "555-0117",
                            SupplierName = "Cleaning Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("85f3c6bc-a4a8-4b59-9ce2-2f960c2f4de3"),
                            Auto = 0,
                            ContactName = "Paula Teal",
                            Email = "paula.teal@furnitureworld.com",
                            Phone = "555-0118",
                            SupplierName = "Furniture World"
                        },
                        new
                        {
                            ID_Supplier = new Guid("ffab429b-b9e1-4020-bcbb-093d6b684142"),
                            Auto = 0,
                            ContactName = "Quinn Brown",
                            Email = "quinn.brown@gardensupplies.com",
                            Phone = "555-0119",
                            SupplierName = "Garden Supplies"
                        },
                        new
                        {
                            ID_Supplier = new Guid("de5ca043-7fe1-4ff2-963e-10035018d805"),
                            Auto = 0,
                            ContactName = "Rachel Silver",
                            Email = "rachel.silver@digitalsolutions.com",
                            Phone = "555-0120",
                            SupplierName = "Digital Solutions"
                        });
                });

            modelBuilder.Entity("DBase.Models.Warehouse", b =>
                {
                    b.Property<Guid>("ID_Warehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ID_Warehouse");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            ID_Warehouse = new Guid("18424185-38c4-494d-99a1-9243c270528c"),
                            Auto = 0,
                            Capacity = 50000,
                            Location = "Downtown",
                            ManagerName = "Alice Johnson",
                            WarehouseName = "Central Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("0bb9f8e0-0500-40e8-88f8-62b1d6b4b451"),
                            Auto = 0,
                            Capacity = 30000,
                            Location = "North District",
                            ManagerName = "Bob Smith",
                            WarehouseName = "Northside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("f458867f-fb75-423a-910c-893bb4d79c9f"),
                            Auto = 0,
                            Capacity = 40000,
                            Location = "East District",
                            ManagerName = "Charlie Brown",
                            WarehouseName = "Eastside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("f6df8f8f-9eb0-4332-a1a6-5707ba8003d9"),
                            Auto = 0,
                            Capacity = 35000,
                            Location = "West District",
                            ManagerName = "Diana Prince",
                            WarehouseName = "Westside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("fedf9557-059f-4eea-b5b0-29203109e14b"),
                            Auto = 0,
                            Capacity = 4500,
                            Location = "South District",
                            ManagerName = "Ethan Hunt",
                            WarehouseName = "Southside Warehouse"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("b879b027-9089-4574-a773-7bcd5b150b3f"),
                            Auto = 0,
                            Capacity = 6000,
                            Location = "Industrial Park",
                            ManagerName = "Fiona Green",
                            WarehouseName = "Logistics Hub"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("58e3105d-db58-4960-ab72-de93a731a60a"),
                            Auto = 0,
                            Capacity = 7000,
                            Location = "Airport Road",
                            ManagerName = "George White",
                            WarehouseName = "Distribution Center"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("29733313-63c1-4b11-bcbe-43ab106b1259"),
                            Auto = 0,
                            Capacity = 2500,
                            Location = "Suburban Area",
                            ManagerName = "Hannah Blue",
                            WarehouseName = "Storage Facility"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("74795400-2abb-40bf-9a3c-88d7bcccd648"),
                            Auto = 0,
                            Capacity = 2000,
                            Location = "Market Street",
                            ManagerName = "Ian Gray",
                            WarehouseName = "Cold Storage"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("0d21dfff-cea4-4304-9306-0e4beb5950b1"),
                            Auto = 0,
                            Capacity = 8000,
                            Location = "Port Area",
                            ManagerName = "Julia Red",
                            WarehouseName = "Bulk Storage"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("5660eaea-4240-4362-9b13-403a765bbc54"),
                            Auto = 0,
                            Capacity = 1000,
                            Location = "Location A",
                            ManagerName = "Manager A",
                            WarehouseName = "Warehouse 1"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("e60a4bcd-9372-4524-a3b8-7fe95158b845"),
                            Auto = 0,
                            Capacity = 2000,
                            Location = "Location B",
                            ManagerName = "Manager B",
                            WarehouseName = "Warehouse 2"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("c6aef0fe-4974-41ba-bfd7-7502ebb9967a"),
                            Auto = 0,
                            Capacity = 1500,
                            Location = "Location C",
                            ManagerName = "Manager C",
                            WarehouseName = "Warehouse 3"
                        },
                        new
                        {
                            ID_Warehouse = new Guid("548245ff-5cb1-48bc-a855-43c744f2fc35"),
                            Auto = 0,
                            Capacity = 2500,
                            Location = "Location D",
                            ManagerName = "Manager D",
                            WarehouseName = "Warehouse 4"
                        });
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.HasOne("DBase.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBase.Models.OrderDetail", b =>
                {
                    b.HasOne("DBase.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBase.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.HasOne("DBase.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBase.Models.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DBase.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DBase.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DBase.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DBase.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DBase.Models.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
