@API_HostAddress = http://localhost:5132

### Add Order and OrderDetails
POST {{API_HostAddress}}/api/Orders HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "CustomerID": "079803a8-edfd-480f-8727-a9f68a0695b7",
    "OrderDetails": [
        {
            "ProductId": "18344cc7-03b8-4a3a-8aee-6f2cd6fb2156",
            "Quantity": 2,
            "UnitPrice": 35.00
        },
        {
            "ProductId": "225cb8bf-0d64-4e14-a3c5-9bf0aabf19c8",
            "Quantity": 1,
            "UnitPrice": 25.00
        }
    ]
}
### Get Order
Get {{API_HostAddress}}/api/Orders/166c07bf-b0a0-4383-8d27-9c8900dcff3b HTTP/1.1
Accept: application/json
Content-Type: application/json

### Get Orders
Get {{API_HostAddress}}/api/Orders HTTP/1.1
Accept: application/json
Content-Type: application/json

### Update an Order
PUT {{API_HostAddress}}/api/Orders/166c07bf-b0a0-4383-8d27-9c8900dcff3b HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "ID_Order": "166c07bf-b0a0-4383-8d27-9c8900dcff3b",
    "CustomerID": "4876cb7e-bd37-4b2c-95cf-f102aaa028fa",
    "TotalAmount": 100.00,
    "Status": "Shipped"
}

### Delete an Order
DELETE {{API_HostAddress}}/api/orders/00959b56-1b6c-4224-b463-2bb8283f25ce HTTP/1.1

### Options for Orders
OPTIONS {{API_HostAddress}}/api/orders HTTP/1.1