@API_HostAddress = http://localhost:5132

### Get Suppliers
Get {{API_HostAddress}}/api/suppliers HTTP/1.1
Accept: application/json
Content-Type: application/json

### POST Supplier
POST {{API_HostAddress}}/api/suppliers HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "SupplierName": "Supplier C",
    "ContactName": "Mark",
    "Email": "mark@supplier.com",
    "Phone": "099-766-4444"
}

### Delete an Supplier
DELETE {{API_HostAddress}}/api/suppliers/01fca1c4-08fd-4005-b368-2ac70d061501 HTTP/1.1
